
var bgPage,pubid="AddThis",pco="crx-200",contextMenuTitle="AddThis";var targets={};$(document).ready(function(){setTimeout(function(){chrome.browserAction.setIcon({path:chrome.extension.getURL('images/19x19-full.png')});},100);bgPage=chrome.extension.getBackgroundPage();injectContentScript(null);window.setTimeout(function(){populateShareMenu('sharemenu',pubid);},100);});function showOptions(){chrome.tabs.create({url:"../../options/options.html"});}
function sharePage(targetName,pub,pageUrl,pageTitle,tabId){var url=encodeURIComponent(pageUrl);var title=encodeURIComponent(pageTitle);var target=targets[targetName];var shareUrl;if(["print","favorites","mailto"].indexOf(targetName)>-1){specialTarget(tabId,targetName,pub,url,title);}
else if(targetName=="more"){shareUrl="http://api.addthis.com/oexchange/0.8/forward/offer?url="+url;if(title)
shareUrl+="&title="+title;shareUrl+="&username="+pub+"&pco="+pco;chrome.tabs.create({url:shareUrl});}
else if(target!=null){shareUrl=target.buildShareUrl(url,title,pub,pco);chrome.tabs.create({url:shareUrl});}}
function shareThisPage(targetName,pub){chrome.windows.getLastFocused(function(focusedWindow){var focusedWindowId=focusedWindow.id;chrome.tabs.getSelected(focusedWindowId,function(tab){sharePage(targetName,pub,tab.url,tab.title,tab.id);});});}
function specialTarget(tabId,target,pub,shareUrl,shareTitle){switch(target){case"print":chrome.tabs.update(tabId,{url:window.print()});break;case"favorites":alert("Press <Control> + D to bookmark");break;case"mailto":chrome.tabs.update(tabId,{url:'mailto:?subject='+shareTitle+'&body='+shareUrl});break;default:return;}}
function getPreferredTargets(){return bgPage.getFinalPreferredTargets();}
function populateShareMenu(divId,pub){var shareDoc=document;var menuDiv=shareDoc.getElementById(divId);targets={};targets=getPreferredTargets();for(var name in targets){var target=targets[name];if(target.name){var targetImg=document.createElement('img');targetImg.setAttribute("src",target.icon16Url);var targetItem=document.createElement('div');targetItem.setAttribute('class',"menu-target-item");targetItem.setAttribute('href',"");targetItem.setAttribute('title',target.prompt);targetItem.setAttribute('onclick',"shareThisPage('"+target.name+"','"+pub+"');");targetItem.appendChild(targetImg);$(targetItem).append('<span>'+target.prompt+'</span>');menuDiv.appendChild(targetItem);}}
$('#sharemenu').append('<div class="menu-target-item" href="" title="More Sharing Destinations" onclick="shareThisPage(\'more\',\''+pub+'\');"><img src="http://cache.addthiscdn.com/icons/v1/thumbs/more.gif"><span>More...</span></div>');$('#sharemenu').append('<div id="footer"><div id="options" title="Configure Services" onclick="javascript:showOptions();return false;">Options</div></div>');$(".menu-target-item").hover(function(evt){$(this).addClass("menu-item-selected");},function(evt){$(this).removeClass("menu-item-selected");});}