var reprompt_callback=null;var reprompt_error_callback=null;function do_submit(){var B=fix_username(document.getElementById("u").value);var G=document.getElementById("p").value;var A=make_lp_hash(B,G);var F=make_lp_key(B,G);if(reprompt_callback!=null){var C=getBG();if(F==C.g_local_key){var E=0;if(document.getElementById("donotrepromptfor").checked){E=document.getElementById("donotrepromptforsecs").value}C.lpPutUserPref("reprompttime",E);C.lpWriteAllPrefs();C.set_last_reprompt_time();reprompt_error_callback=null;
C.select_selectedtabid();reprompt_callback();setTimeout("window.close();",0)}else{alert(gs("Invalid Password."));setTimeout("getBG().closecurrenttab('login.html');",0)}}else{var D=getBG();if(!D){alert(gs("Can't find hidden LastPass window"));return}D.LP_do_login(B,G,document.getElementById("rememberemail").checked,document.getElementById("rememberpassword").checked,null,document.getElementById("showvault").checked);reprompt_error_callback=null;setTimeout(function(){getBG().closecurrenttab("login.html")
},0)}return false}var passwords=new Array();function load(C){try{if(!C){get_data("login",function(){load(true)});return}var E=getBG();if(!can_chrome_do_math()){E.openURL(getchromeurl("mathfail.html"))}if(E.g_reprompt_callback!=null){reprompt_callback=E.g_reprompt_callback;E.g_reprompt_callback=null;reprompt_error_callback=E.g_reprompt_error_callback;E.g_reprompt_error_callback=null;document.getElementById("reprompttext").style.display="";document.getElementById("deleteicon").style.display="none";
document.getElementById("rememberemailrow").style.display="none";document.getElementById("rememberpasswordrow").style.display="none";document.getElementById("showvaultrow").style.display="none";document.getElementById("donotrepromptforrow").style.display="";document.getElementById("u").value=E.g_username;document.getElementById("u").disabled=true;var G=E.lpGetPref("reprompttime",0);document.getElementById("donotrepromptfor").checked=G>0;document.getElementById("donotrepromptforsecs").value=G;document.getElementById("p").focus();
document.getElementById("links").style.display="none"}else{var B=E.lpGetPref("rememberemail",1);var A=E.lpGetPref("rememberpassword",-1);var F=E.lpGetPref("showvault",-1);document.getElementById("rememberemail").checked=B==1?true:false;document.getElementById("rememberpassword").checked=A==1?true:false;document.getElementById("showvault").checked=F==1?true:false;getBG().g_db_transaction_tested=getBG().g_db_transaction_worked=false;var D=opendb();if(!D){D=opendb()}createSavedLoginsTable(D);if(D){D.transaction(function(I){getBG().g_db_transaction_tested=getBG().g_db_transaction_worked=true;
I.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(M,O){var N=new Array();for(var Q=0;Q<O.rows.length;Q++){N[Q]=O.rows.item(Q)["username"];passwords[N[Q]]=O.rows.item(Q)["password"];if(O.rows.item(Q)["protected"]){passwords[N[Q]]=getBG().unprotect_data(passwords[N[Q]])}}N.sort(function(T,S){return T.toLowerCase()<S.toLowerCase()?-1:1});create_combo("u",N);var K="";var J=document.location.href.indexOf("sesameusername=");if(J!=-1){K=document.location.href.substr(J+15);
J=K.indexOf("&");if(J!=-1){K=K.substring(0,J)}K=decodeURIComponent(K)}if(O.rows.length>0||K!=""){var R=K!=""?K:O.rows.item(0)["username"];var P=typeof(passwords[R])!="undefined"?passwords[R]:"";document.getElementById("u").value=R;document.getElementById("p").focus();if(P!=""){document.getElementById("p").value=P;if(A==-1){document.getElementById("rememberpassword").checked=true}document.getElementById("login").focus()}}else{document.getElementById("u").focus()}},function(J,K){console_log(K)})});
if(g_ischrome){if(navigator.userAgent.indexOf("Chrome/4")!=-1||navigator.userAgent.indexOf("Chrome/5")!=-1){setTimeout("test_db_failed(1);",5000)}}}else{test_db_failed(0)}}}catch(H){console_log(H)}}function test_db_failed(A){L("test_db_failed timeout: "+A);getBG().g_db_transaction_tested=true;if(!getBG().g_db_transaction_worked){document.getElementById("nodbtext").style.display="";document.getElementById("u").focus();create_combo("u",new Array())}}function username_changed(){var A=document.getElementById("u").value;
if(typeof(passwords[A])!="undefined"&&passwords[A]!=""){document.getElementById("p").value=passwords[A];document.getElementById("rememberpassword").checked=true}else{document.getElementById("p").value="";document.getElementById("rememberpassword").checked=false}}function delete_user(){var C=document.getElementById("u").value;var A=opendb();createSavedLoginsTable(A);if(A){A.transaction(function(D){D.executeSql("DELETE FROM LastPassSavedLogins2 WHERE username=?",[C])})}delete passwords[C];delete_combo_item("u",C);
document.getElementById("u").value="";for(var B in passwords){document.getElementById("u").value=B;break}username_changed()}function retsubmit(B){var A=B.keyCode;if(13==A){do_submit();return false}return true};