
var isCtrl=false;jQuery.fn.swapWith=function(to){return this.each(function(){var copy_to=$(to).clone(true);var copy_from=$(this).clone(true);$(to).replaceWith(copy_from);$(this).replaceWith(copy_to);});};$(document).ready(function(){if(localStorage["addthis_sshp"]==undefined){localStorage["addthis_sshp"]="facebook,myspace,google,twitter,digg,delicious,email,stumbleupon";}
var prefServices=localStorage["addthis_sshp"].split(',');for(var i=0;i<prefServices.length;i++){if(prefServices[i])
createIcon(prefServices[i],false,"services");}
$(document).keydown(function(event){isCtrl=event.keyCode=='17'?true:false;});$(document).keyup(function(event){if(event.keyCode=='17'){isCtrl=false;}});$("#services").append('<div class="clearer"></div>');$("#submitbtn").click(function(){updateSSH();$(".savedChanges").html("Changes successfully saved.");$(".savedChanges").show("slow");setTimeout(function(){$(".savedChanges").hide("slow");},4000);var bgpage=chrome.extension.getBackgroundPage();bgpage.populateContextMenu();});$("#resetbtn").click(function(){var c=confirm("Are you sure you want to reset your services?");if(c){localStorage.removeItem("addthis_sshp");location.reload();}
var bgpage=chrome.extension.getBackgroundPage();bgpage.populateContextMenu();});$("#addServiceBtn").click(function(){var availSlots=$("#add-services .selected").size()+$("#services .service-icon").size();$("#add-services .selected").each(function(){var id=$(this).attr("id");createIcon(id,true,"services");});var availSlots=$("#services .service-icon").size();while(availSlots>11){var removed=$("#services .service-icon:last");removed.remove();$("#add-services").append(removed);availSlots--;}
$("#add-services .selected").remove();sortServices();});$("#removeServiceBtn").click(function(){$("#services .selected").each(function(){id=$(this).attr("id");});var removed=$("#services .selected");removed.appendTo($("#add-services"));removed.removeClass("selected");$("#services .selected").remove();sortServices();});$("#upBtn").click(function(){var e=$("#services .selected");if(e.prev().attr("title")!==undefined)
e.swapWith(e.prev());});$("#downBtn").click(function(){var e=$("#services .selected");if(e.next().attr("title")!="")
e.swapWith(e.next());});$("#services").droppable({accept:'.add-service-item',tolerance:'pointer',drop:function(evt,ui){$service=ui.draggable;var serviceId=$item.attr("id");$(this).removeClass("service-bg");$("#"+serviceId).remove();$(ui.helper).remove();$("#services .service-icon:last").remove();createIcon(serviceId,true,"add-services");},over:function(evt,ui){$item=ui.draggable;$(this).addClass("service-bg");},out:function(evt,ui){$item=ui.draggable;$(this).removeClass("service-bg");}});});function createIcon(service,drop,div){var serviceTitle=(addthis.util.getServiceName(service));var iconWrap=$('<div class="service-icon" id="'+service+'" title="'+service+'" onclick="toggleSelected($(this))"><span class="addthis_service_icon icon_'+service+'">'+serviceTitle+'</span></div>');drop==true?iconWrap.hide().prependTo('#'+div).fadeIn("slow"):iconWrap.hide().appendTo('#'+div).fadeIn("slow");}
function findService(item){var idx,arr=localStorage["addthis_sshp"].split(',');for(var i=0;i<arr.length;i++){idx=(item==arr[i])?i:-1;if(-1!=idx)break;}
return idx;}
function sortServices(){$("#add-services .service-icon").tsort("span");}
function toggleSelected(e){var p=e.parent().attr("id");if(!isCtrl){$("#"+p+" .service-icon").removeClass("selected");e.addClass("selected");}else if(e.hasClass("selected")&&isCtrl){e.removeClass("selected");}else{e.addClass("selected");}}
function makeSortable(){$("#services").sortable({cursor:"move",containment:"parent",opacity:".7",placeholder:"service-icon-empty",change:function(e,ui){ui.item.toggleClass("selected");},update:function(e,ui){}});}
function displayResponse(response){$(function(){appendServices(response.data);});}
function appendServices(services){var i=0,mod=10,sleep=100,service_els=$('#add-services');while(services.length){var service=services.shift();var found=findService(service.code);if(found==-1)
createIcon(service.code,false,"add-services");}
setTimeout(function(){appendServices(services);},sleep);}
function updateSSH(){var s=[];$("#services .service-icon").each(function(){s.push($(this).attr("title"));});localStorage["addthis_sshp"]=s;}