var g_CS={},g_CS_count={},g_CS_tabs={},g_nexttabid=1,poll_timeout=6E4,debug=true,g_local_key=null,g_local_hash=null,g_username=null,g_username_hash=null,g_uid=null,g_pwdeckey=null,g_token="",g_identity="",g_sites=[],g_tlds=[],g_securenotes=[],g_prompts=[],g_local_accts_version=-1,g_server_accts_version=-1,g_identities=[],g_formfills=[],g_neverurls=[],g_equivalentdomains=[],g_urlrules=[],g_prefoverrides=[],g_pendings=[],g_shareeautopushes=[],g_shareeautopushests=0,g_loglogins=false,g_isadmin=false,
g_launches=[],ischrome=true,g_icons=[],g_icons_length=0,g_loggedinoffline=false,g_loggedinonline=false,g_notification_type=null,g_notification_data=null,g_site_data=null,g_formfill_data=null,g_reprompt_callback=null,g_reprompt_error_callback=null,g_omnikey_callback=null,g_last_reprompt_time=0,g_premium_exp=0,g_lastpollcheck=0,g_lastpoll=0,g_logoff_other_ses=false,g_generatedpw=false,g_gblprefs=[],g_userprefs=[],g_fillfieldsmatches=[],g_fillfieldsmatchescurridx=[],g_currenturl="",g_currenttabid="",
g_badgedata=null,g_saveall_url,g_saveall_framestotal,g_saveall_framesdone,g_saveall_docnumsdone,g_saveall_formdata,g_genpws=[],g_lp_hotkeys=["generateHk","recheckHk","searchHk","nextHk","prevHk","homeHk","submitHk","saveallHk","logoffHk","defaultffidHk"],g_generate_url="",g_generate_url_prev="",g_changepwnewpw="",g_changepwtld="",g_curr_fill_aid=0,g_is_win=navigator.appVersion.indexOf("Windows")!=-1,g_is_mac=navigator.appVersion.indexOf("Mac")!=-1,g_is_linux=navigator.appVersion.indexOf("Linux")!=
-1,g_retryonlinetimerid=null,g_notifytimerid=null,g_loggedLogins=[],g_master_password_saved=false,g_create_account_data=null,g_nplastpass=null,g_loginstarted=false,g_persistent_notifications=[],g_rejectedaddsites=[],g_checkgeneratepasswordcallback=null,g_db_transaction_tested=false,g_db_transaction_worked=false,g_hidevault=false,g_hidenotes=false,g_hideidentities=false,g_hideexport=false,g_hideimport=false,g_hidesharing=false,g_hideprint=false,lp_rsaprivatekeyhex="",lp_rsaprivatekeyenchex="",lp_rsaprivatekeyenchexserverhash=
"",g_selectedtabid=-1,g_selectedtab=null,g_export_output="",g_editfieldsopener=null,g_currenttld=null,SpecialSites={};function lpobjrejectedaddsite(){}var g_opera_button=null,g_username_vals=[];function have_nplastpass(a){try{g_nplastpass||(g_nplastpass=document.getElementById("nplastpass"));g_nplastpass.is_chrome_portable();return typeof g_nplastpass.alert!="undefined"&&(a||navigator.userAgent.indexOf("Chrome/4.1.249.1042")==-1)}catch(b){return false}}
function command_handler(a){if(a.command=="LPToolButtonClick")if(lploggedin){update_menus();toggle_menu()}else openURL(getchromeurl("login.html"))}function gettabid(a){if(g_ischrome)return a.id;else if(g_issafari){if(typeof a.myData=="undefined"){a.myData=g_nexttabid++;g_CS_tabs[a.myData]=a}return a.myData}else if(g_isopera){for(var b in g_CS_tabs)if(g_CS_tabs[b].url==a.url)return b;b=g_nexttabid++;g_CS_tabs[b]=a;return b}}
function get_all_windows(a,b){if(g_ischrome)chrome.windows.getAll(a,b);else if(g_issafari)b(safari.application.browserWindows);else g_isopera&&b(opera.extension.windows.getAll())}function get_tabs_length(a){try{return a.tabs.length}catch(b){return 0}}
function close_tab(a){get_all_windows({populate:true},function(b){b.length==1&&get_tabs_length(b[0])==1&&gettabid(b[0].tabs[0])==gettabid(a)&&openURL("about:tabs");if(g_ischrome)chrome.tabs.remove(gettabid(a));else if(g_issafari||g_isopera)a.close()})}function cleanup_tabs(){if(g_issafari)for(var a in g_CS)for(var b in g_CS[a]){if(typeof g_CS[a][b].browserWindow=="undefined"||!g_CS[a][b].browserWindow){delete g_CS[a];typeof g_CS_tabs[a]!="undefined"&&delete g_CS_tabs[a]}break}}
function get_selected_tab(a,b){if(g_ischrome)chrome.tabs.getSelected(a,b);else if(g_issafari)b(safari.application.activeBrowserWindow.activeTab);else if(g_isopera)if(opera.extension.tabs.getFocused())b(opera.extension.tabs.getFocused());else return false;return true}
function message_handler(a){if(g_isopera){a.message=a.data;a.name=a.data.messagetype}var b=false;if(typeof a.message.g_user_prefs_to_write!="undefined"){b=true;var c=LPJSON.parse(a.message.g_user_prefs_to_write),d;for(d in c)lpPutUserPref(d,c[d])}if(typeof a.message.g_global_prefs_to_write!="undefined"){b=true;c=LPJSON.parse(a.message.g_global_prefs_to_write);for(d in c)lpPutGblPref(d,c[d])}b&&lpWriteAllPrefs();if(a.name=="connect"){var e=false,f=gettabidfromevent(a);if(a.message.name==geteventtargeturl(a)){cleanup_tabs();
g_CS[f]=[];g_CS_count[f]=0;g_loggedLogins=[];e=true}if(typeof g_CS[f]=="undefined"||!g_CS[f]){g_CS[f]=[];g_CS_count[f]=0}b=a.message.docnum;g_CS[f][b]=geteventtarget(a);g_CS_count[f]++;lpGetPref("language","");d=localStorage.getItem("ff.dat");sendCS(f,{cmd:"setdocnum",docnum:b,language_data:g_language_data,ff:d==null?"":d},b);e&&typeof g_persistent_notifications[f]!="undefined"&&g_persistent_notifications[f]&&sendCS(f,g_persistent_notifications[f])}else if(a.name=="focus"){e=lp_gettld_url(a.message.url);
if(!compare_tlds(e,g_currenttld)){update_menus();g_currenttld=e}}else if(a.name=="message")receiveCS(gettabidfromevent(a),a.message,0,{tab:geteventtarget(a)});else if(a.name=="LP_do_login")LP_do_login(a.message.u,a.message.p,a.message.rememberemail,a.message.rememberpassword,a.message.donotclearmultifactor,a.message.showvault);else if(a.name=="openURL"){if(typeof a.message.g_site_data!="undefined"){g_site_data=LPJSON.parse(a.message.g_site_data);g_site_data.fields=g_sites[g_site_data.aid].fields}openURL(a.message.url)}else if(a.name==
"reprompt_callback"){set_last_reprompt_time();g_reprompt_callback_save()}else if(a.name=="reprompt_error_callback")g_reprompt_error_callback_save();else if(a.name=="omnikey_callback")g_omnikey_callback_save(a.message.pin);else if(a.name=="update_prefs")if(a.message.page=="prefs"){lpGetPref("storeLostOTP")||DeleteOTP();if(lpGetPref("logoffWhenCloseBrowser")||lpGetPref("idleLogoffVal")>0)lpGetPref("rememberpassword")==0&&deletesavedpw(g_username);start_idle_checker();setprefs("all","all")}else{if(a.message.page==
"generate")g_genpws=a.message.g_genpws}else if(a.name=="update_prompts")g_prompts=LPJSON.parse(a.message.g_prompts);else if(a.name=="openall")openall(a.message.group);else if(a.name=="deleteGroup")deleteGroup(a.message.group,null,function(){event_dispatch_message(a,"delete_group_callback",{})});else if(a.name=="copyusername")copyusername(a.message.aid);else if(a.name=="copypassword")copypassword(a.message.aid);else if(a.name=="deleteAid")deleteAid(a.message.aid,null,false,false,function(){event_dispatch_message(a,
"delete_aid_callback",{})});else if(a.name=="editAid")editAid(a.message.aid);else if(a.name=="gotourl")gotourl(a.message.aid);else if(a.name=="launch")launch(a.message.aid);else if(a.name=="open_login")open_login(a.message.forcetab);else if(a.name=="addprofile")addprofile();else if(a.name=="addcreditcard")addcreditcard();else if(a.name=="editprofile")editprofile(a.message.ffid);else if(a.name=="openprefs")openprefs(a.message.tab);else if(a.name=="openbaseurl")openbaseurl(a.message.suffix);else if(a.name==
"changemasterpassword")changemasterpassword();else if(a.name=="openaddsecurenote")openaddsecurenote();else if(a.name=="loggedOut")loggedOut(a.message.skiprequest,a.message.from);else if(a.name=="switch_identity")switch_identity(a.message.iid);else if(a.name=="renameGroup")renameGroup(a.message.origgrp,a.message.newgrp);else if(a.name=="addEmptyGroup")addEmptyGroup(a.message.newgrp);else if(a.name=="moveSelectedToGroup")moveSelectedToGroup(a.message.group,a.message.aids);else if(a.name=="security_prompt")security_prompt(function(){event_dispatch_message(a,
"security_prompt_callback",{})});else if(a.name=="savePassword")savePassword(a.message.pass,a.message.url,a.message.tabid,a.message.nofill);else if(a.name=="checkgeneratepassword"){g_checkgeneratepasswordcallback=function(){event_dispatch_message(a,"generatepasswordfound",{})};sendCS(a.message.tabid,{cmd:"checkgeneratepassword"})}else if(a.name=="fillform")fillform(a.message.ffid,false,a.message.origtabid,a.message.ccffid);else if(a.name=="changePassword")changePassword(a.message.password,a.message.aids);
else if(a.name=="receiveTS")receiveTS(null,a.message);else if(a.name=="deleteformfill")deleteformfill(a.message.ffid);else if(a.name=="addeditformfill")addeditformfill(LPJSON.parse(a.message.ffdata),LPJSON.parse(a.message.site));else if(a.name=="fix_tlds")fix_tlds(a.message.oldtld,a.message.newtld,a.message.aid);else if(a.name=="increment_local_accts_version")increment_local_accts_version();else if(a.name=="rewritelocalfile")rewritelocalfile();else if(a.name=="saveSite")saveSite(a.message.postdata,
fix_fields(LPJSON.parse(a.message.acct)));else if(a.name=="saveAllSite")saveAllSite(a.message.postdata,fix_fields(LPJSON.parse(a.message.acct)));else if(a.name=="saveSiteFromSubmit")saveSiteFromSubmit(a.message.postdata,fix_fields(LPJSON.parse(a.message.acct)));else if(a.name=="saveFields")saveFields(a.message.getdata,a.message.postdata,fix_fields(LPJSON.parse(a.message.aData)));else if(a.name=="set_editfieldsopener")set_editfieldsopener(geteventtarget(a));else if(a.name=="close_editfieldsopener")close_editfieldsopener();
else if(a.name=="unprotect_data")event_dispatch_message(a,"unprotect_data_callback",{protected_data:a.message.data,unprotected_data:unprotect_data(a.message.data)});else if(a.name=="update_site"){e=fix_fields(LPJSON.parse(a.message.site));if(e.sn)g_securenotes[e.aid]=e;else g_sites[e.aid]=e}else if(a.name=="update_fields"){g_sites[a.message.aid].fields=LPJSON.parse(a.message.fields);g_sites[a.message.aid]=fix_fields(g_sites[a.message.aid])}else if(a.name=="select_selectedtabid")select_selectedtabid();
else if(a.name=="closecurrenttab")closecurrenttab(a.message.page);else if(a.name=="add_identity")add_identity();else if(a.name=="checkforupdates")checkforupdates();else if(a.name=="clearforms")clearforms();else if(a.name=="clearrecent")clearrecent();else if(a.name=="openabout")openabout();else if(a.name=="openaddsite")openaddsite();else if(a.name=="openchooseprofilecc")openchooseprofilecc();else if(a.name=="openexport")openexport();else if(a.name=="openfavorites")openfavorites();else if(a.name=="openfeedback")openfeedback();
else if(a.name=="opengenpw")opengenpw();else if(a.name=="openhelp")openhelp();else if(a.name=="openimport")openimport();else if(a.name=="openimportchrome")openimportchrome();else if(a.name=="openlastpassexport")openlastpassexport();else if(a.name=="openpremium")openpremium();else if(a.name=="opensearch")opensearch();else if(a.name=="openseccheck")openseccheck();else if(a.name=="opensessions")opensessions();else if(a.name=="openvault")openvault();else if(a.name=="recheckpage")recheckpage();else if(a.name==
"refreshsites")refreshsites();else if(a.name=="saveall")saveall();else if(a.name=="upgradetoserver")upgradetoserver();else if(a.name=="clearCache")clearCache(a.message.noprompt);else if(a.name=="deleteNever")deleteNever(LPJSON.parse(a.message.n));else if(a.name=="fillaid")fillaid(a.message.aid);else if(a.name=="openprint")openprint(a.message.notes);else if(a.name=="getdata"){b={g_userprefsstr:LPJSON.stringify(g_userprefs),g_gblprefsstr:LPJSON.stringify(g_gblprefs),g_username:g_username,ischrome:ischrome,
LPISLOC:LPISLOC,LPISUPEK:LPISUPEK,LPISUPEKCAPABLE:LPISUPEKCAPABLE,lp_iscbc:lp_iscbc,g_promptsstr:LPJSON.stringify(g_prompts)};switch(a.message.page){case "login":if(g_reprompt_callback){b.g_reprompt_callback="g_reprompt_callback";g_reprompt_callback_save=g_reprompt_callback;g_reprompt_callback=null;b.g_local_key=g_local_key}if(g_reprompt_error_callback){b.g_reprompt_error_callback="g_reprompt_error_callback";g_reprompt_error_callback_save=g_reprompt_error_callback;g_reprompt_error_callback=null}break;
case "omnikey":if(g_omnikey_callback){b.g_omnikey_callback="g_omnikey_callback";g_omnikey_callback_save=g_omnikey_callback;g_omnikey_callback=null}break;case "export":b.g_export_output=g_export_output;g_export_output="";break;case "prefs":b.g_is_win=g_is_win;b.g_is_linux=g_is_linux;b.g_is_mac=g_is_mac;b.g_pref_tab=g_pref_tab;g_pref_tab=null;b.g_master_password_saved=g_master_password_saved;b.base_url=base_url;f=[];for(e=0;e<g_formfills.length;e++)if(check_ident_ffid(g_formfills[e].ffid))f[f.length]=
g_formfills[e];b.g_formfills=LPJSON.stringify(f);b.g_have_nplastpass=have_nplastpass();b.g_prefoverrides=LPJSON.stringify(g_prefoverrides);break;case "vault":b.g_username=g_username;b.g_local_accts_version=g_local_accts_version;b.lploggedin=lploggedin;b.g_identity=g_identity;b.g_isadmin=g_isadmin;b.g_icons_length=g_icons_length;b.recentCount=getRecentCount();if(typeof a.message.g_username=="undefined"||g_username!=a.message.g_username||g_local_accts_version>a.message.g_local_accts_version||lploggedin!=
a.message.lploggedin||g_identity!=a.message.g_identity||g_isadmin!=a.message.g_isadmin){b.g_hideidentities=g_hideidentities;b.g_identities=LPJSON.stringify(g_identities);c=[];for(e in g_sites)if(check_ident_aid(g_sites[e].aid))c[e]=g_sites[e];b.g_sites=LPJSON.stringify(c);d=[];for(e in g_securenotes)if(check_ident_aid(g_securenotes[e].aid))d[e]=g_securenotes[e];b.g_securenotes=LPJSON.stringify(d);f=[];for(e=0;e<g_formfills.length;e++)if(check_ident_ffid(g_formfills[e].ffid))f[f.length]=g_formfills[e];
b.g_formfills=LPJSON.stringify(f);f=[];for(e=0;e<g_pendings.length;e++)if(check_ident_aid(g_pendings[e].aid))f[f.length]=g_pendings[e];b.g_pendings=LPJSON.stringify(f);b.g_username_hash=g_username_hash;b.maxnotesizeb64=get_searchNotesB64Length();b.lpclearrecent=lpclearrecent;b.g_icons_length=g_icons_length;b.clearRecentTime=getClearRecentTime();b.g_icons=LPJSON.stringify(g_icons);b.g_local_key=g_local_key}break;case "toolstrip":case "toolstripchangepw":b.g_generate_url=g_generate_url;if(g_generate_url!=
"")g_generate_url_prev=g_generate_url;g_generate_url="";b.g_changepwnewpw=g_changepwnewpw;b.g_changepwtld=g_changepwtld;b.lploggedin=lploggedin;b.g_genpws=g_genpws;b.g_local_key=g_local_key;b.g_badgedata=g_badgedata;b.g_premium_exp=g_premium_exp;b.g_hideexport=g_hideexport;b.g_hideidentities=g_hideidentities;b.g_hideimport=g_hideimport;b.g_hidenotes=g_hidenotes;b.g_hideprint=g_hideprint;b.g_identity=g_identity;b.clearRecentTime=getClearRecentTime();c=[];for(e in g_sites)if(check_ident_aid(g_sites[e].aid))c[e]=
g_sites[e];b.g_sites=LPJSON.stringify(c);d=[];for(e in g_securenotes)if(check_ident_aid(g_securenotes[e].aid))d[e]=g_securenotes[e];b.g_securenotes=LPJSON.stringify(d);var g=getcurrenturl();d=getsites(a.message.page=="toolstripchangepw"?g_changepwtld:lp_gettld_url(g));if(a.message.page=="toolstrip")d=reorderOnURL(d,g);e=[];for(f in d)e[d[f].aid]=g_sites[d[f].aid];b.g_sites_tld=LPJSON.stringify(e);f=[];for(e=0;e<g_formfills.length;e++)if(check_ident_ffid(g_formfills[e].ffid))f[f.length]=g_formfills[e];
b.g_formfills=LPJSON.stringify(f);b.g_identities=LPJSON.stringify(g_identities);b.g_nevers=LPJSON.stringify(getnevers());b.g_icons=LPJSON.stringify(g_icons);b.g_menuheight=getmenuheight(true,true,true,true);break;case "formfill":b.g_formfill_data=LPJSON.stringify(g_formfill_data);g_formfill_data=null;b.countryfromip=countryfromip;b.g_generatedpw=g_generatedpw;b.lploggedin=lploggedin;b.g_local_key=g_local_key;break;case "site":g=g_site_data.url;b.g_site_data=LPJSON.stringify(g_site_data);g_site_data=
null;b.g_generatedpw=g_generatedpw;b.g_local_key=g_local_key;c=[];for(e in g_sites)if(check_ident_aid(g_sites[e].aid))c[e]=g_sites[e];b.g_sites=LPJSON.stringify(c);d=getsites(lp_gettld_url(g),true);c=[];for(f in d)c[f]=g_sites[f];b.g_sites_tld=LPJSON.stringify(c);d=[];for(e in g_securenotes)if(check_ident_aid(g_securenotes[e].aid))d[e]=g_securenotes[e];b.g_securenotes=LPJSON.stringify(d);b.lploggedin=lploggedin;b.g_prompts=g_prompts;break;case "about":b.g_have_nplastpass=have_nplastpass()}event_dispatch_message(a,
"gotdata",b)}}function update_menus(){if(g_issafari)for(var a=0;a<safari.extension.bars.length;a++)if(safari.extension.bars[a].identifier=="LPMenu"){safari.extension.bars[a].label=gs("LastPass Menu");safari.extension.bars[a].contentWindow.redraw_menu();lploggedin||safari.extension.bars[a].hide()}}
function toggle_menu(a){for(var b=0;b<safari.extension.bars.length;b++)if(safari.extension.bars[b].browserWindow==safari.application.activeBrowserWindow&&safari.extension.bars[b].identifier=="LPMenu")a||safari.extension.bars[b].visible?safari.extension.bars[b].hide():safari.extension.bars[b].show()}function close_menu(){toggle_menu(true)}
function onLoad(){L("BG : loaded");if(g_isopera){g_opera_button=opera.contexts.toolbar.createItem({disabled:false,title:"LastPass",icon:"icon_gray2.gif",popup:{width:"1px",height:"1px",href:getchromeurl("lp_toolstrip.html?browseraction=1")}});opera.contexts.toolbar.addItem(g_opera_button);opera.extension.tabs.onfocus=function(){var b=opera.extension.tabs.getFocused();b=b?b.url:"";if(b!=""&&b.indexOf("widget")==-1){g_generate_url_prev=g_generate_url;g_generate_url=b;opera.postError("######################################################### Setting bg.g_generate_url="+
g_generate_url)}else if(g_generate_url==""&&g_generate_url_prev!=""){g_generate_url=g_generate_url_prev;opera.postError("######################################################### Setting B bg.g_generate_url="+g_generate_url_prev)}else opera.postError("######################################################### NOT changing bg.g_generate_url="+g_generate_url)}}if(g_issafari){safari.application.addEventListener("command",command_handler,false);safari.application.addEventListener("message",message_handler,
false)}else g_isopera&&opera.extension.addEventListener("message",message_handler,false);var a=false;have_nplastpass()&&typeof g_nplastpass.lpvt_setup_if=="function"&&g_nplastpass.lpvt_setup_if();if(have_nplastpass()&&typeof g_nplastpass.file_exists=="function"){if(g_nplastpass.file_exists("LPISLOC"))if(g_nplastpass.lpvt_verify_file_contents(g_nplastpass.read_file("LPISLOC")))LPISLOC=true;else a=true;if(g_nplastpass.file_exists("LPISUPEK"))if(g_nplastpass.lpvt_verify_file_contents(g_nplastpass.read_file("LPISUPEK")))LPISUPEK=
true;else a=true;if(g_nplastpass.file_exists("LPISUPEKCAPABLE"))if(g_nplastpass.lpvt_verify_file_contents(g_nplastpass.read_file("LPISUPEKCAPABLE")))LPISUPEKCAPABLE=true;else a=true}a&&alert(gs("LastPass has detected an installation error.  Please reinstall LastPass."));g_ischrome&&typeof chrome.browserAction.setPopup=="function"&&chrome.browserAction.onClicked.addListener(function(){open_login(true)});drawIconAtRotation(0);g_hidevault=get_registry_value("Software\\LastPass","hidevault","0")=="1";
g_hidenotes=get_registry_value("Software\\LastPass","hidenotes","0")=="1";g_hideidentities=get_registry_value("Software\\LastPass","hideidentities","0")=="1";g_hideexport=get_registry_value("Software\\LastPass","hideexport","0")=="1";g_hideimport=get_registry_value("Software\\LastPass","hideimport","0")=="1";g_hidesharing=get_registry_value("Software\\LastPass","hidesharing","0")=="1";g_hideprint=get_registry_value("Software\\LastPass","hideprint","0")=="1";if(LPISLOC)g_hideidentities=g_hidesharing=
g_hideprint=true;lpReadAllPrefs(function(b){if(b==0)if(g_ischrome){lpPutGblPref("welcomedone",1);lpWriteAllPrefs();LPISLOC||openURL(getchromeurl("welcome.html"))}lpGetPref("enablenamedpipes",1)==1&&have_nplastpass()&&lpnp_init();if(LPISLOC||!g_np_init)httptest()});setup_poll_timer();DeleteOldDynamicFiles();getchromeurl("needtoreinstall.html").indexOf("kegdhfdpgckamaoikbjiemmikleploeh")!=-1&&openURL(base_url+"/needtoreinstall.html");have_nplastpass()&&typeof g_nplastpass.setup_basicauth_timer=="function"&&
g_nplastpass.setup_basicauth_timer();LoadSpecialSites()}
g_ischrome&&chrome.extension.onConnect.addListener(function(a){var b=false;if(a.name==a.tab.url){g_CS[a.tab.id]=[];g_CS_count[a.tab.id]=0;g_loggedLogins=[];b=true}if(typeof g_CS[a.tab.id]=="undefined"||!g_CS[a.tab.id]){g_CS[a.tab.id]=[];g_CS_count[a.tab.id]=0}var c=g_CS[a.tab.id].length;g_CS[a.tab.id][c]=a;g_CS_count[a.tab.id]++;var d=localStorage.getItem("ff.dat");sendCS(a.tab.id,{cmd:"setdocnum",docnum:c,ff:d==null?"":d},c);b&&typeof g_persistent_notifications[a.tab.id]!="undefined"&&g_persistent_notifications[a.tab.id]&&
sendCS(a.tab.id,g_persistent_notifications[a.tab.id]);a.onMessage.addListener(function(e,f){receiveCS(f.tab.id,e,0,a)});a.onDisconnect.addListener(function(e){receiveCS(e.tab.id,null,1,a)})});function disconnectCS(a){if(typeof g_CS[a]!="undefined"&&g_CS[a]){for(var b in g_CS[a]){g_CS[a][b].disconnect();g_CS[a][b]=null}g_CS_count[a]=0}}
function sendCS(a,b,c){if(a=="all")for(var d in g_CS)for(var e in g_CS[a])try{sendCS(d[e],b)}catch(f){b.cmd=="saveall"&&g_saveall_framestotal--}else if(typeof g_CS[a]=="undefined"||!g_CS[a])L("BG -> CS["+a+"] : FAILED");else{e=true;for(d in g_CS[a]){if(typeof c=="undefined"){if(!e)continue;e=false}else if(c!="all"&&c!=d)continue;try{if(g_ischrome)g_CS[a][d].postMessage(b);else if(g_issafari){b.docnum=d;g_CS[a][d].page.dispatchMessage("message",b)}else if(g_isopera){b.docnum=d;b.messagetype="message";
g_CS[a][d].postMessage(b)}}catch(g){}}}}function receiveCS(a,b,c,d){if(c){if(--g_CS_count[a]<=0)g_CS[a]=null}else if(typeof b.cmd=="undefined")L("CS["+a+"] -> BG : INVALIDMSG");else processCS(a,b,d)||L("CS["+a+"] -> BG : INVALIDMSG")}
function sendTS(a,b){if(!(g_issafari||g_isopera))try{a.cmd=="notification"&&a.type!="upgrade"&&set_badge(a);if(!(a.cmd!="notification"||a.type!="upgrade")){var c=typeof b=="undefined"?"all":b,d=false,e=chrome.extension.getViews(),f;for(f in e)if(typeof e[f].receiveBG=="function"&&(c=="all"||typeof e[f].g_toolstripid!="undefined"&&c==e[f].g_toolstripid)){L("BG -> TS : cmd="+a.cmd);e[f].receiveBG(a);d=true;if(c!="all")break}d||L("BG -> TS : FAILED")}}catch(g){L("BG -> TS : FAILED error="+g)}}
function set_badge(a){if(!(g_issafari||g_isopera)){chrome.browserAction.setBadgeText({text:"1"});g_badgedata=a;currrotation=0;animateFlip()}}function clear_badge(){if(!(g_issafari||g_isopera)){chrome.browserAction.setBadgeText({text:""});currrotation=numrotations;g_badgedata=null;drawIconAtRotation(0)}}
function receiveTS(a,b){if(typeof b.cmd=="undefined"){L("TS["+a+"] -> BG : INVALIDMSG");return null}L("TS["+a+"] -> BG : cmd="+b.cmd);switch(b.cmd){case "getloginstate":lploggedin&&sendTS({cmd:"login"},a);break;case "sesameauth":sesame_auth(b.otp,b.label);break;case "yubikeyauth":yubikey_auth(b.otp,b.label);break;case "gridauth":grid_auth(b.gridvalues,b.label);break;case "multifactorauth":multifactor_auth(["multifactorresponse"],b.label);break;case "lostkey":lostkey();break;case "sesamelostkey":sesamelostkey();
break;case "gridlostkey":gridlostkey();break;case "multifactorlostkey":multifactorlostkey(b.type);break;case "turnofficon":lpTurnOffIcon();break;default:L("TS["+g_toolstripid+"] -> BG : INVALIDMSG");return null}}function omnikey_get_pin(a){g_omnikey_callback=a;openURL(getchromeurl("omnikey.html"))}
function processCS(a,b,c){switch(b.cmd){case "rsadecrypt":if(lp_url_is_lastpass(b.url)){c=b.sharekeyenchex;var d="";if(!b.sharerpublickeyhex||!c){sendCS(a,{cmd:"rsadecrypt",rc:"rsaerror",sharekeyhex:""});break}}break;case "plug2web":if(lp_url_is_lastpass(b.url)){d=lpParseUri(b.url);c=d.directory;d=d.file;c=c.replace(/^\/~[^\/]*/,"");if(c!=""&&c!="/"&&c!="/sso/"&&c!="/sso/webroot/"&&c!="/sso/aso/"){lpdbg("error","Keyplug2web request from invalid directory: "+c);break}d=d.replace(/#/,"");if(d!=""&&
d!="index.php"&&d!="import.php"&&d!="export.php"&&d!="otp.php"&&d!="frameset.php"&&d!="frame_login.php"&&d!="gettopost.php"&&d!="misc_challenge.php"&&d!="enterprise_users.php"){lpdbg("error","Keyplug2web request from invalid file: "+d);break}if(g_username!=null&&g_username!="")b.username&&b.username!=""&&fix_username(b.username)!=fix_username(g_username)?loggedOut(false,"plug2webA"):sendCS(a,{cmd:"plug2web",username:g_username,key:AES.bin2hex(g_local_key),version:lpversion,identity:g_identity},b.docnum)}break;
case "web2plug":lp_url_is_lastpass(b.url)&&web2plug(b);break;case "logoff":lp_url_is_lastpass(b.url)&&lploggedin&&loggedOut(false,"logoff");break;case "login":lp_url_is_lastpass(b.url)&&loginfromwebsite(b);break;case "fill":case "autofillaid":case "autologinaid":b.topurl=c.tab.url;handleFill(a,b);break;case "checkgenpwfillforms":checkgenpwfillforms(a,b.url);break;case "neverautofill":case "neverpage":case "neverdomain":handleNever(a,b);if(typeof b.fromsave!="undefined"){g_persistent_notifications[a]=
null;c=b.notificationdata.username;d=b.notificationdata.password;lpAddRejectedSite(c,d,b.tld);clear_badge()}break;case "clearnotification":clear_badge();g_persistent_notifications[a]=null;break;case "notnow":c=b.notificationdata.username;d=b.notificationdata.password;lpAddRejectedSite(c,d,b.tld);g_persistent_notifications[a]=null;clear_badge();break;case "savethesite":c=b.notificationdata;c.addsite=1;g_site_data=c;openURL(getchromeurl("site.html"));g_persistent_notifications[a]=null;clear_badge();
break;case "changepw":c=b.notificationdata;c.sitecount==1?changePassword(c.newpw,Array(c.singleaid)):openchangepw(c.newpw,c.tld);g_persistent_notifications[a]=null;clear_badge();break;case "save":handleSave(a,b);break;case "updatefields":handleUpdateFields(a,b);break;case "addurid":handleAddUrid(a,b);break;case "saveall":if(typeof g_saveall_docnumsdone[b.docnum]=="undefined"){g_saveall_docnumsdone[b.docnum]=1;g_saveall_formdata+=b.formdata;++g_saveall_framesdone>=g_saveall_framestotal&&handleSaveAll(a,
{cmd:"saveall",addsite:1,url:g_saveall_url,formdata:g_saveall_formdata});console_log(g_saveall_framesdone+"|"+g_saveall_framestotal)}break;case "clearcache":lp_url_is_lastpass(b.url)&&clearCache(true,false,false);break;case "recover":console_log("username in bg "+b.username);lp_url_is_lastpass(b.url)&&recover(a,b.url,b.username,b.docnum);break;case "launchautologin":lp_url_is_lastpass(b.url)&&launchautologin(b.aid);break;case "getprefs":g_username_vals[b.url]=b.username_val;setprefs(a,b.docnum);break;
case "getuuid":sendCS(a,{cmd:"setuuid",uuid:getuuid()},b.docnum);break;case "setupmultifactor":b.tabid=a;if(b.username==g_username){var e="type="+LP.en(b.type)+"&username="+LP.en(b.username);lpMakeRequest(base_url+"setupmultifactor.php",e,lpSetupMultifactorResponse,function(){lpSetupMultifactorError(b)},b)}else sendCS(a,{cmd:"setupmultifactor",result:"error"},b.docnum);break;case "setupsinglefactor":b.tabid=a;if(b.username==g_username){e="type="+LP.en(b.type)+"&username="+LP.en(b.username);var f=
true,g=function(){if(f)lpMakeRequest(base_url+"setupmultifactor.php",e,lpSetupMultifactorResponse,function(){lpSetupMultifactorError(b)},b);else b.silent!="1"&&sendCS(a,{cmd:"setupsinglefactor",result:"error"},b.docnum)};b.type=="omnikey"?omnikey_get_pin(function(k){var j="";if(have_nplastpass()&&typeof g_nplastpass.omnikey_get_public_key=="function")j=g_nplastpass.omnikey_get_public_key(k);if(j=="")f=false;else e+="&secret="+encodeURIComponent(j);g()}):g()}else b.silent!="1"&&sendCS(a,{cmd:"setupsinglefactor",
result:"error"},b.docnum);break;case "checkmultifactorsupport":c="";d="error";if(have_nplastpass()&&typeof g_nplastpass.validity_supported=="function"&&g_nplastpass.validity_supported()){c="validity";d="done"}else if(have_nplastpass()&&typeof g_nplastpass.omnikey_supported=="function"&&g_nplastpass.omnikey_supported()){c="omnikey";d="done"}else if(have_nplastpass()&&typeof g_nplastpass.trueapi_supported=="function"&&g_nplastpass.trueapi_supported()){c="trueapi";d="done"}else if((LPISUPEK||LPISUPEKCAPABLE)&&
have_nplastpass()&&typeof g_nplastpass.lpvt_supported=="function"&&g_nplastpass.lpvt_supported()){c="vtapi";d="done"}sendCS(a,{cmd:"checkmultifactorsupport",type:c,result:d},b.docnum);break;case "multifactorauth":var h="";if(b.type=="trueapi"){c=SHA256(SHA256(fix_username(b.username)+b.type));if(c.length!=64)if(have_nplastpass()&&typeof g_nplastpass.trueapi_get_hash=="function")c=g_nplastpass.trueapi_get_hash(b.username);if(c!="")h=SHA256(c+b.challenge)}else if(b.type=="omnikey"){omnikey_get_pin(function(){if(have_nplastpass()&&
typeof g_nplastpass.omnikey_decrypt=="function")h=g_nplastpass.omnikey_decrypt(b.username);sendCS(a,{cmd:"multifactorauth",multifactorresponse:h,result:h!=""?"done":"error"},b.docnum)});return}sendCS(a,{cmd:"multifactorauth",multifactorresponse:h,result:h!=""?"done":"error"},b.docnum);break;case "multifactorreprompt":security_prompt(function(){sendCS(a,{cmd:"multifactorauth",result:"done"},b.docnum)},function(){sendCS(a,{cmd:"multifactorauth",result:"error"},b.docnum)});break;case "refresh":if(lp_url_is_lastpass(b.url))b.from==
"settings"?lplogincheck(b.type=="2"?"websiterefreshrsa":"websiterefresh"):get_accts();break;case "switchidentity":lp_url_is_lastpass(b.url)&&switch_identity(b.iid,true,true);break;case "fillfieldconfirm":fillfieldsconfirm(b);break;case "deleteaid":deleteAid(b.aid,null,true,true);break;case "runhotkey":switch(b.hotkey){case "generateHk":opengenpw();break;case "recheckHk":recheckpage();break;case "searchHk":opensearch();break;case "nextHk":fillnext(1);break;case "prevHk":fillnext(-1);break;case "homeHk":openvault();
break;case "submitHk":fillnext(0,true);break;case "saveallHk":saveall();break;case "logoffHk":loggedOut(false,"hotkey");break;case "defaultffidHk":fill_default_ffid()}break;case "reporterror":lpReportError(b.e,"");break;case "fillformffid":fillform(b.ffid);break;case "addprofile":addprofile();break;case "addcreditcard":addcreditcard();break;case "clearforms":clearforms();break;case "chooseprofilecc":openchooseprofilecc();break;case "generate":opengenpw();break;case "fillcurrentaid":fillcurrent(b.aid);
break;case "generatepasswordfound":if(g_checkgeneratepasswordcallback){g_checkgeneratepasswordcallback();g_checkgeneratepasswordcallback=null}break;case "log":console_log(b.msg);break;case "disablebtn":openURL(base_url+b.notificationdata.multifactor_disable_url);break;case "createaccountbtn":if(g_ischrome)openURL(getchromeurl("welcome.html"));else if(g_issafari||g_isopera)openURL(base_url+"create_account.php");break;case "tryagainbtn":open_login();break;case "feedbackbtn":openfeedback();break;case "basicauthneverbtn":lpPutUserPref("basicauthnever",
"1");lpWriteAllPrefs();break;case "basicauthmoreinfobtn":have_nplastpass()?openURL(base_url+"chromebasicauth.php"):openURL(base_url+"lpchrome_bin.crx");break;case "gohome":if(g_ischrome)chrome.tabs.update(a,{url:getchromeurl("homelocal.html")});else if(g_issafari)c.tab.url=getchromeurl("homelocal.html");else g_isopera&&c.tab.update({url:getchromeurl("homelocal.html")});if(b.email!=""&&b.sesameotp!=""){lplog("LOGGING OFF : gohome");lplogoff();sesame_setotp(b.sesameotp);openURL(getchromeurl("login.html?sesameusername="+
encodeURIComponent(b.email)))}break;default:L("CS["+a+"] -> BG : INVALIDMSG");return false}return true}
function open_login(){var a=getsinglefactortype();if(a=="trueapi"&&have_nplastpass()&&typeof g_nplastpass.trueapi_default_login_exists=="function"&&g_nplastpass.trueapi_default_login_exists()){var b={},c={},d={};if(g_nplastpass.trueapi_get_default_login(b,c,d)){multifactor_setdata("password_offline",d.value);multifactor_setdata("type",a);LP_do_login(b.value,c.value,false,false,true);return false}}if(LPISUPEK||a=="vtapi"){if(have_nplastpass()&&typeof g_nplastpass.lpvt_verify_user=="function"){b=encodeURIComponent(lpCreatePass(8,
1,1,1,0,1,0,1));b=g_nplastpass.lpvt_verify_user(b,gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"),gs("Swipe current user's finger"));if(b!=""){b=b.split("|");if(b.length==2){LP_do_login(decodeURIComponent(b[0]),decodeURIComponent(b[1]));return false}}}if(LPISUPEK&&LPISLOC){have_nplastpass()&&typeof g_nplastpass.lpvt_has_data=="function"&&g_nplastpass.lpvt_has_data()?lpshowError("LoginError",false,true):lpshowError("Before you can use LastPass, you must first connect your fingerprint reader and enroll one or more fingers.",
false,true);return false}}if(a=="validity")if(have_nplastpass()&&typeof g_nplastpass.validity_verify_user=="function"){b=g_nplastpass.validity_verify_user("",gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"));if(b!=""){b=b.split("|");if(b.length==2){LP_do_login(decodeURIComponent(b[0]),decodeURIComponent(b[1]));return false}}}openURL(getchromeurl("login.html"))}
function fillnext(a,b){lploggedin?get_selected_tab(null,function(c){getBG().setcurrenttabid(gettabid(c));getBG().setcurrenturl(c.url);c=getmatchingsites(1);if(c.length>0){for(var d=0;d<c.length;d++)if(c[d].aid==g_curr_fill_aid)break;if(d==c.length)g_curr_fill_aid=a==-1?c[c.length-1].aid:c[0].aid;else{if(a==1){if(++d>=c.length)d=0}else if(a==-1)if(--d<0)d=c.length-1;g_curr_fill_aid=c[d].aid}b?fill(getcurrenttabid(),g_sites[g_curr_fill_aid],null,true,false,"all",false,false,true):fillaid(g_curr_fill_aid)}}):
open_login()}function getInt(a){a=parseInt(a);if(a==""||a==NaN)a=0;return a}
function loggedIn(a){L("BG : loggedIn");lploggedin=true;lpReadAllPrefs(postlogin);if(typeof localStorage!="undefined"){var b=localStorage.getItem(db_prepend("lastversion"));checkOpenUpgradePage(b);localStorage.setItem(db_prepend("lastversion"),lpversion);b=opendb();createSavedLoginsTable(b);b&&b.transaction(function(c){c.executeSql("SELECT * FROM LastPassSavedLogins2 WHERE username = ? AND password != ''",[g_username],function(d,e){if(e.rows.length>0)g_master_password_saved=true},function(){})});
a&&setTimeout("refresh_windows();",500);drawIconAtRotation(0);sendTS({cmd:"login"})}}
function checkOpenUpgradePage(a){var b=lpversion,c=0,d=0,e=0,f=0;if(a)for(var g=a.split("."),h=0;h<g.length;h++)if(h==0)c=parseInt(g[h]);else if(h==1)d=parseInt(g[h]);else h==2&&parseInt(g[h]);b=b.split(".");for(h=0;h<b.length;h++)if(h==0)e=parseInt(b[h]);else if(h==1)f=parseInt(b[h]);else h==2&&parseInt(b[h]);if(a&&a!="null"&&(e>c||f>d))openURL(base_url+"upgrade.php?ver="+lpversion+"&type="+encodeURIComponent(get_method())+"&upgrade="+a)}
function get_searchNotesB64Length(){var a=0,b=lpGetPref("searchNotesVal",200);if(lpGetPref("searchNotes",1)==1&&b>0){a=Math.floor((4*b-3)/3);if(a%64!=0)a=a-a%64+64}return a}function postlogin(){g_lastpollcheck=(new Date).getTime();if(lpGetPref("logoffWhenCloseBrowser",0)==1&&lpGetPref("logoffWhenCloseBrowserVal",0)>0){lpPutUserPref("lastpollcheck",g_lastpollcheck);lpWriteAllPrefs()}}function lplogin(){openURL(getchromeurl("login.html"))}function lplogoff(){loggedOut(false,"lplogoff")}
function lplogoff_if(){lploggedin&&loggedOut(false,"lplogoff_if")}var rotation=0,numrotations=504,currrotation=0;function animateFlip(){rotation+=1/36;if(rotation>=1)rotation-=1;if(++currrotation>=numrotations)rotation=0;else setTimeout("animateFlip()",10);drawIconAtRotation(rotation)}
function drawIconAtRotation(a){if(g_issafari){for(a=0;a<safari.extension.toolbarItems.length;a++)if(safari.extension.toolbarItems[a].identifier.indexOf("LPToolButton")!=-1)safari.extension.toolbarItems[a].image=getchromeurl(lploggedin?"icon_on.png":"icon_off.png");update_menus()}else if(g_isopera)setTimeout(function(){if(lploggedin){if(g_opera_button.icon!="icon2.gif"){g_opera_button.icon="icon2.gif";g_opera_button.popup.width="450px";g_opera_button.popup.height="450px";g_opera_button.popup.href=
getchromeurl("lp_toolstrip.html?browseraction=1")}}else if(g_opera_button.icon!="icon_gray2.gif"){g_opera_button.icon="icon_gray2.gif";g_opera_button.popup.width="1px";g_opera_button.popup.height="1px";g_opera_button.popup.href=getchromeurl("lp_toolstrip.html?browseraction=1")}},0);else{var b=document.getElementById(g_badgedata!=null?g_badgedata.cmd=="notification"&&g_badgedata.type=="save"?"icon_green":"icon_yellow":lploggedin?"icon":"icon_gray"),c=document.getElementById("canvas").getContext("2d");
c.save();c.clearRect(0,0,19,19);c.translate(9,9);c.rotate(2*Math.PI*ease(a));c.drawImage(b,-b.width/2,-b.height/2);c.restore();chrome.browserAction.setIcon({imageData:c.getImageData(0,0,19,19)});if(typeof chrome.browserAction.setPopup=="function")chrome.browserAction.setPopup({popup:lploggedin||g_badgedata!=null?"lp_toolstrip.html?browseraction=1":""})}}function ease(a){return(1-Math.sin(Math.PI/2+a*Math.PI))/2}
function lpAddRejectedSite(a,b,c){var d=new lpobjrejectedaddsite;d.username=a;d.encryptedPassword=lpenc(b);d.tld=c;d.rejectedTime=lp_get_gmt_timestamp();g_rejectedaddsites[g_rejectedaddsites.length]=d}
function loggedOut(a,b){L("BG : loggedOut from="+b);get_all_windows({populate:true},function(d){for(var e=0;e<d.length;e++)for(var f=0;f<get_tabs_length(d[e]);f++){var g=d[e].tabs[f].url;g&&lp_url_is_lastpassext(g)&&g.indexOf("homelocal.html")==-1&&g.indexOf("welcome.html")==-1&&g.indexOf("mathfail.html")==-1&&g.indexOf("login.html")==-1&&close_tab(d[e].tabs[f])}});lploggedin&&lpnp_notify("logout");closeallnotifications();yubikey_cleardata();sesame_cleardata();grid_cleardata();multifactor_cleardata();
lpSaveData("","key");var c=false;if(!lploggedin)c=a=true;lploggedin=false;last_idle_check=0;g_pwdeckey=g_uid=lpuid=g_username_hash=g_username=g_local_hash=g_local_key=null;g_sites=[];g_tlds=[];g_securenotes=[];g_prompts=[];g_icons=[];g_icons_length=0;g_server_accts_version=g_local_accts_version=-1;g_identities=[];g_pendings=[];g_shareeautopushes=[];g_formfills=[];g_neverurls=[];g_equivalentdomains=[];g_urlrules=[];g_prefoverrides=[];g_isadmin=g_loglogins=false;g_launches=[];g_fillfieldsmatches=[];
g_fillfieldsmatchescurridx=[];g_loggedinonline=g_loggedinoffline=false;lp_phpsessid="";g_premium_exp=0;g_loginstarted=false;lpReadAllPrefs();rotation=0;drawIconAtRotation();if(g_badgedata!=null&&(g_badgedata.cmd!="notification"||g_badgedata.type!="error"))clear_badge();rsa_clearvars();rsa_setpendingsharests(true);g_genpws=[];g_master_password_saved=false;g_persistent_notifications=[];g_rejectedaddsites=[];lpdisableoffline=false;countryfromip="";sendTS({cmd:"logoff"});c||setTimeout("refresh_windows();",
500);a||lpMakeRequest(base_url+"logout.php?chrome_plugin=1&noredirect=1","",null,null)}function getmenurowheight(){return 20}function getmatchingsitesheight(a){a=a.length*getmenurowheight();if(a>200)a=200;return a}
function getmenuheight(a,b,c,d){var e=15;g_premium_exp>lp_get_local_timestamp()&&--e;var f=getmenurowheight();e=e*f;if(typeof a=="undefined"||a){a=getmatchingsites();if(a.length>0){e+=f;e+=getmatchingsitesheight(a)}}if(typeof b=="undefined"||b)e+=32;if(typeof c=="undefined"||c)e+=15;if(d)e-=50;return e}function fillaid(a,b){var c=b?true:false;setTimeout(function(){fill(getcurrenttabid(),g_sites[a],null,false,true,"all",true,c,true)},100)}function setcurrenturl(a){g_currenturl=a}
function setcurrenttabid(a){g_currenttabid=a}function getmatchingsites(){var a=getcurrenturl();lpcanonizeUrl(a);var b=lp_gettld_url(a);b=getsites(b);b=reorderOnURL(b,a);var c,d;a=[];for(c in b){d=b[c].aid;if(typeof g_sites[d]!="undefined"){d=g_sites[d];a.push({aid:d.aid,name:d.name,username:getusernamefromacct(d),fiid:d.fiid})}}return a}
function getnevers(){var a=getcurrenturl(),b=lp_gettld_url(a);a=lpcanonizeUrl(a);var c=[];getneverfor(c,"neveraccounts",a,b);getneverfor(c,"neverautologins",a,b);getneverfor(c,"neverformfills",a,b);getneverfor(c,"nevergenerates",a,b);return c}function getneverfor(a,b,c,d){if(g_neverurls[b]&&g_neverurls[b].length>0)for(var e=0;g_neverurls[b]&&e<g_neverurls[b].length;e++){var f=g_neverurls[b][e];if(f==c)a.push({type:b,url:f,domain:0});else f==d&&a.push({type:b,url:f,domain:1})}}
function getpasswordfromacct(a){if(a.save_all){for(var b=0;b<a.fields.length;b++)if(a.fields[b].type=="password"&&a.fields[b].value!="")return lpmdec(a.fields[b].value,true);return""}else return typeof a.password!="undefined"?lpmdec(a.password,true):""}
function getsites(a,b){var c;if(typeof g_equivalentdomains[a]!="undefined"){var d=g_equivalentdomains[a];if(typeof g_equivalentdomains[d]!="undefined")c=g_equivalentdomains[d]}else c=Array(a);d=[];for(var e=0;e<c.length;e++)if(typeof g_tlds[c[e]]!="undefined")for(var f in g_tlds[c[e]])b&&g_sites[f].genpw||(d[f]=g_tlds[c[e]][f]);return d}
function accthaspassword(a){if(a.save_all){for(var b=0;b<a.fields.length;b++)if(a.fields[b].type=="password"&&a.fields[b].value!="")return true;return false}else return a.password!=""}function lp_url_is_lastpass(a){return a.indexOf(base_url)==0||a.indexOf("https://lastpass.com/")==0?true:false}function lp_url_is_lastpassext(a){var b=getchromeurl("");if(a&&a.indexOf(b)==0)return true;return false}
function openvault(a){if(!a&&!lploggedin)open_login();else a?get_all_windows({populate:true},function(b){for(var c=0;c<b.length;c++)for(var d=0;d<get_tabs_length(b[c]);d++)if(b[c].tabs[d].url==getchromeurl("homelocal.html"))return;openURL(getchromeurl("homelocal.html"))}):openURL(getchromeurl("homelocal.html"))}function openimport(){openURL(base_url+"import.php?hasplugin="+LP.en(lpversion)+get_identity_param())}function openimportchrome(){openURL(getchromeurl("import.html"))}
function openexport(){doexport()}
function openlastpassexport(a){if(lpGetPref("noexport",0)==1)alert(gs("CompanyPolicyProhibits"));else{if(!g_generatedpw)if(!a){security_prompt(function(){openlastpassexport(true)});return}if(have_nplastpass()&&typeof g_nplastpass.write_file=="function"&&typeof g_nplastpass.get_path=="function"){rewritelocalfile(false,true,true);alert(gs("Your data has been exported to")+"\n"+g_nplastpass.get_path()+"lpexport.xml")}else alert(gs("The binary version of the LastPass plugin is required for this operation. It can be downloaded from lastpass.com."))}}
function openprint(a){var b=base_url+"export.php?plug=1&print=1&hasplugin="+LP.en(lpversion)+get_identity_param();if(a)b+="&notes=1";openURL(b)}g_pref_tab=null;function openprefs(a){if(a)g_pref_tab=a;openURL(getchromeurl(g_isopera?"options.html":"prefs.html"))}function openhelp(){openURL(base_url+"help.php?fromwebsite=1")}function openpremium(){openURL(base_url+"premium.php")}
function openall(a,b){if(a==gs("favorites"))openfavorites();else if(a==gs("recently usedlower"))openallrecent();else{var c=[],d=false,e;for(e in g_sites)if(check_ident_aid(g_sites[e].aid))if(g_sites[e].group==a){c.push(g_sites[e]);d|=g_sites[e].pwprotect}if(c.length!=0)if(!b&&(d||g_prompts.login_site_prompt))security_prompt(function(){openall(a,true)});else for(e=0;e<c.length;e++){d=c[e];openURL(d.url,function(f,g){console_log("setting aid "+gettabid(f)+" "+g);g_launches[gettabid(f)]=g},d.aid,true)}}}
function openallrecent(a){var b=[],c;for(c in g_sites)check_ident_aid(g_sites[c].aid)&&b.push(g_sites[c]);b.sort(function(f,g){return f.last_touch>g.last_touch?1:-1});var d=[],e=false;for(c=0;d.length<10&&c<b.length;c++)if(b[b.length-c-1].url!="http://group"){e|=b[b.length-c-1].pwprotect;d[d.length]=b[b.length-c-1]}if(d.length!=0)if(!a&&(e||g_prompts.login_site_prompt))security_prompt(function(){openallrecent(true)});else for(c=0;c<d.length;c++){a=d[c];openURL(a.url,function(f,g){console_log("setting aid "+
gettabid(f)+" "+g);g_launches[gettabid(f)]=g},a.aid,true)}}function openfavorites(a){var b=[],c=false,d;for(d in g_sites)if(check_ident_aid(g_sites[d].aid))if(g_sites[d].fav=="1"){b.push(g_sites[d]);c|=g_sites[d].pwprotect}if(b.length!=0)if(!a&&(c||g_prompts.login_site_prompt))security_prompt(function(){openfavorites(true)});else for(d=0;d<b.length;d++){a=b[d];openURL(a.url,function(e,f){console_log("setting aid "+gettabid(e)+" "+f);g_launches[gettabid(e)]=f},a.aid,true)}}
function saveall(){lploggedin?get_selected_tab(null,function(a){g_saveall_url=a.url;g_saveall_framestotal=g_CS_count[gettabid(a)];g_saveall_framesdone=0;g_saveall_docnumsdone=[];g_saveall_formdata="";sendCS(gettabid(a),{cmd:"saveall"},"all")}):open_login()}function openfeedback(){openURL(base_url+"feedback.php")}
function opengenpw(){get_selected_tab(null,function(a){if(g_generate_url!="")g_generate_url_prev=g_generate_url;g_generate_url=a.url;openURL(getchromeurl("lp_toolstrip.html?browseraction=1&generate=1&tabid="+en(gettabid(a))))})}function openchooseprofilecc(){get_selected_tab(null,function(a){a=gettabid(a);openURL(getchromeurl("lp_toolstrip.html?browseraction=1&chooseprofilecc=1&tabid="+en(a)))})}
function openchangepw(a,b){g_changepwnewpw=a;g_changepwtld=b;openURL(getchromeurl("lp_toolstrip.html?browseraction=1&changepw=1"))}function opensearch(){lploggedin?openURL(getchromeurl("home.html")):open_login()}function recheckpage(){lploggedin?get_selected_tab(null,function(a){a=gettabid(a);sendCS(a,{cmd:"recheck"},"all")}):open_login()}function refreshsites(){get_accts()}
function clearAllData(){var a=opendb();createDataTable(a);a&&a.transaction(function(b){b.executeSql("DELETE FROM LastPassData"+(LPISLOC?" WHERE type != 'key' AND type != 'accts'":""),[],function(){console_log("DESTROYING LastPassDatang Table")},function(c,d){console_log(d)})})}
function clearCache(a,b,c){if(typeof b=="undefined")b=true;if(typeof c=="undefined")c=true;if(!(g_username==null||g_username=="")){if(!LPISLOC){typeof localStorage!="undefined"&&localStorage.removeItem(db_prepend(g_username_hash+"_lt.cac"));if(have_nplastpass()&&typeof g_nplastpass.delete_file=="function"){g_nplastpass.delete_file(db_prepend(g_username_hash)+"_lt.cac");g_nplastpass.delete_file(db_prepend(g_username_hash)+"_lpall.slps");g_nplastpass.delete_file(db_prepend(g_username_hash)+"_lpall.lps")}}var d=
"";b||(d+=" AND type != 'icons' AND type != 'rsakey'");c||(d+=" AND type != 'otp'");if(LPISLOC)d+=" AND type != 'key' AND type != 'accts'";c=opendb();createDataTable(c);c&&c.transaction(function(e){e.executeSql("UPDATE LastPassData SET username_hash=? WHERE username_hash=?"+d,["deleteme",db_prepend(g_username_hash)],function(){var f=opendb();createDataTable(f);f&&f.transaction(function(g){g.executeSql("DELETE FROM LastPassData WHERE username_hash=?"+d,["deleteme"],function(){},function(h,k){console_log(k)})})},
function(f,g){console_log(g)})});if(b){b=lpreadretryfile();if(b!=null&&b.length>0){b=gs("A retry file has been found. This likely means that not all of your site changes have been saved. Would you like to delete this file and potentially lose some changes?");if(a||confirm(b))lpdeleteretry()}}}}function openabout(){openURL(getchromeurl("about.html"))}function opensessions(){openURL(base_url+"sess.php")}function openseccheck(){openURL(base_url+"?securitychallenge=1")}
function openaddsite(){g_site_data=createNewAcct();g_site_data.addsite="1";g_site_data.noreplace="1";if(!get_selected_tab(null,function(a){g_site_data.url=a.url;openURL(getchromeurl("site.html"))})){g_site_data.url="";openURL(getchromeurl("site.html"))}}function openaddsecurenote(){if(lploggedin){g_site_data=createNewAcct();g_site_data.sn=1;g_site_data.url="http://sn";openURL(getchromeurl("site.html"))}else open_login(1)}
function checkforupdates(){g_notification_type="upgrade";g_notification_data={checking:true};sendTS({cmd:"notification",type:"upgrade"});setTimeout(function(){lpMakeRequest(base_url+"upgrade.php?binary="+(have_nplastpass()?1:0)+"&x=1&ver="+LP.en(lpversion)+(g_issafari?"&safarijs=1":"")+(g_isopera?"&opera=1":""),"",upgrade_response,null)},250)}
function fillform(a,b,c,d){if(check_ident_ffid(a))if(!(d&&!check_ident_ffid(d))){for(var e=0;e<g_formfills.length;e++)if(g_formfills[e].ffid==a)break;if(e!=g_formfills.length){var f;if(d){for(f=0;f<g_formfills.length;f++)if(g_formfills[f].ffid==d)break;if(f==g_formfills.length)return}!b&&(g_formfills[e].pwprotect||d&&g_formfills[f].pwprotect||g_prompts.view_ff_prompt)?get_selected_tab(null,function(g){var h=c?c:gettabid(g);security_prompt(function(){fillform(a,true,h,d)})}):get_selected_tab(null,
function(g){g=c?c:gettabid(g);var h=g_formfills[e],k=d?g_formfills[f]:null,j=[],n=[],i;for(i in h)if(i=="ffid"||i=="profiletype"||i=="pwprotect")j[i]=h[i];else if(i=="custom_fields"){j[i]=[];for(var l=0;l<h[i].length;l++){var m="custom_field"+l;j[m]=[];j[m].cfid=h[i][l].cfid;j[m].text=lpmdec(h[i][l].text,true);j[m].value=lpmdec(h[i][l].value,true);j[m].alttext=lpmdec(h[i][l].alttext,true)}}else if(d&&i.indexOf("cc")==0)j[i]=lpmdec(k[i],true);else{j[i]=lpmdec(h[i],true);if(i=="profilelanguage"&&typeof translations[j[i]]!=
"undefined")n[j[i]]=translations[j[i]]}if(typeof n["en-US"]=="undefined")n["en-US"]=translations["en-US"];i=LPJSON.stringify(j);sendCS(g,{cmd:"fillform",toformfill:i,translations:LPJSON.stringify(translations)},"all");logformfill(a)})}}}function getacceptabletlds(a){var b=a=lp_gettld_url(a),c=null;if(typeof g_equivalentdomains[a]!="undefined")c=g_equivalentdomains[a];if(c)for(var d in g_equivalentdomains)if(d==c)b+=","+g_equivalentdomains[d];return b}
function fillcurrent(a,b,c){!b&&(g_sites[a].pwprotect||g_prompts.login_site_prompt)?get_selected_tab(null,function(d){var e=c?c:gettabid(d);security_prompt(function(){fillcurrent(a,true,e)})}):get_selected_tab(null,function(d){d=c?c:gettabid(d);sendCS(d,{cmd:"fillcurrent",password:getpasswordfromacct(g_sites[a]),domains:getacceptabletlds(g_sites[a].url)},"all")})}function openbaseurl(a){openURL(base_url+a)}
function addprofile(a){if(lploggedin)if(!a&&g_prompts.view_ff_prompt)security_prompt(function(){addprofile(true)});else{g_formfill_data={};g_formfill_data.cmd="add";g_formfill_data.type=0;g_formfill_data.data=null;openURL(getchromeurl("formfill.html"))}else open_login(1)}
function addcreditcard(a){if(lploggedin)if(!a&&g_prompts.view_ff_prompt)security_prompt(function(){addcreditcard(true)});else{g_formfill_data={};g_formfill_data.cmd="add";g_formfill_data.type=1;g_formfill_data.data=null;openURL(getchromeurl("formfill.html"))}else open_login(1)}
function editprofile(a,b){if(lploggedin)for(var c=0;c<g_formfills.length;++c){if(a==g_formfills[c].ffid){if(!b&&(g_formfills[c].pwprotect||g_prompts.view_ff_prompt)){security_prompt(function(){editprofile(a,true)});break}g_formfill_data={};g_formfill_data.cmd="edit";g_formfill_data.type=g_formfills[c].profiletype;g_formfill_data.data=g_formfills[c];openURL(getchromeurl("formfill.html"));break}}else open_login(1)}
function clearforms(){get_selected_tab(null,function(a){a=gettabid(a);sendCS(a,{cmd:"clearforms"},"all")})}function lostkey(){openURL(base_url+"lostkey.php?cmd=sendemail&username="+en(g_username))}function sesamelostkey(){openURL(base_url+"sesamedisable.php?cmd=sendemail&username="+en(g_username))}function gridlostkey(){openURL(base_url+"griddisable.php?cmd=sendemail&username="+en(g_username))}
function multifactorlostkey(a){openURL(base_url+"multifaactordisable.php?cmd=sendemail&username="+en(g_username)+"&type="+en(a))}
function lpshowError(a,b,c,d,e,f){g_notification_type="error";g_notification_data={msg:gs(a),showFeedback:b,showLogin:c,showCreateAccount:d,multifactor_disable_url:e,yellow:f};sendTS({cmd:"notification",type:"error"});setTimeout(function(){get_selected_tab(null,function(g){sendCS(gettabid(g),{cmd:"showerrornotification",text:gs(a),notificationdata:g_notification_data})})},100);console_log(a)}
function launch(a,b){if(check_ident_aid(a)){var c=null;if(g_sites[a])c=g_sites[a];else if(g_securenotes[a])return editAid(a);else return;var d=c.pwprotect;if(!b&&(d||g_prompts.login_site_prompt))security_prompt(function(){launch(a,true)});else{d=c.url;d.match(/^[a-z]+?\:\/\//i)||(d="http://"+d);openURL(d,function(e,f){g_launches[gettabid(e)]=f},c.aid)}}}
function security_prompt(a,b){if(g_prompts.multifactor_reprompt||LPISUPEK){var c=multifactor_getdata("password_offline");if(c&&c!="")if(multifactor_getdata("type")=="trueapi")if(have_nplastpass()&&typeof g_nplastpass.trueapi_get_hash=="function")if(g_nplastpass.trueapi_get_hash(g_username)==c){a();return}c=getsinglefactortype();if(LPISUPEK||c=="vtapi"){if(have_nplastpass()&&typeof g_nplastpass.lpvt_verify_user=="function"){var d=g_nplastpass.lpvt_verify_user("",gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),
gs("Cancel"),gs("Swipe current user's finger"));if(d!=""){d=d.split("|");if(d.length==2)if(g_local_key!=""&&g_local_key==AES.hex2bin(SHA256(fix_username(decodeURIComponent(d[0]))+decodeURIComponent(d[1])))){a();return}}}if(LPISUPEK&&LPISLOC){typeof b=="function"&&b();return}}if(c=="validity")if(have_nplastpass()&&typeof g_nplastpass.validity_verify_user=="function"){d=g_nplastpass.validity_verify_user("",gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"));if(d!=""){d=
d.split("|");if(d.length==2)if(g_local_key!=""&&g_local_key==AES.hex2bin(SHA256(fix_username(decodeURIComponent(d[0]))+decodeURIComponent(d[1])))){a();return}}}}c=lpGetPref("reprompttime",0);if((new Date).getTime()-g_last_reprompt_time<=c*1E3)a();else{g_reprompt_callback=a;g_reprompt_error_callback=b;openURL(getchromeurl("login.html"))}}function get_identity_param(){return"&iid="+LP.en(g_identity)}
function add_ident_aid(a){if(g_identity!=""){for(var b=0;b<g_identities.length;b++)if(g_identities[b].iid==g_identity)break;if(!(b>=g_identities.length)){b=g_identities[b];if(b.aids!="")b.aids+=",";b.aids+=a;b.aidarr=b.aids.split(",")}}}function add_ident_ffid(a){if(g_identity!=""){for(var b=0;b<g_identities.length;b++)if(g_identities[b].iid==g_identity)break;if(!(b>=g_identities.length)){b=g_identities[b];if(b.ffids!="")b.ffids+=",";b.ffids+=a;b.ffidarr=b.ffids.split(",")}}}
function check_ident_aid(a){if(g_identity=="")return true;else{for(var b=0;b<g_identities.length;b++)if(g_identities[b].iid==g_identity)break;if(b>=g_identities.length)return false;b=g_identities[b];if(typeof b.aidarr=="undefined")b.aidarr=b.aids.split(",");return lp_in_array(a,b.aidarr)}}
function check_ident_ffid(a){if(g_identity=="")return true;else{for(var b=0;b<g_identities.length;b++)if(g_identities[b].iid==g_identity)break;if(b>=g_identities.length)return false;b=g_identities[b];if(typeof b.ffidarr=="undefined")b.ffidarr=b.ffids.split(",");return lp_in_array(a,b.ffidarr)}}
function switch_identity(a,b,c,d){if(a!=g_identity){var e=false;if(a!=""){for(var f=0;f<g_identities.length;f++)if(g_identities[f].iid==a){if(g_identities[f].pw_prompt)e=true;break}if(f>=g_identities.length)return}else for(f=0;f<g_identities.length;f++)if(g_identities[f].pw_prompt){e=true;break}if(!b&&(e||g_prompts.switch_identity_prompt))security_prompt(function(){switch_identity(a,true)});else{g_identity=""+a;d||lpnp_notify("switchidentity",{data0:g_identity});lpPutUserPref("identity",g_identity);
lpWriteAllPrefs();c||refresh_windows();update_menus()}}}function add_identity(){openURL(base_url+"?ac=1&addidentity=1")}function setup_poll_timer(){setTimeout("poll_server();",6E4)}function set_last_reprompt_time(){g_last_reprompt_time=(new Date).getTime()}
function compare_tlds(a,b){if(typeof a!="string")return false;if(typeof b!="string")return false;a=a.toLowerCase();b=b.toLowerCase();return a==b?true:typeof g_equivalentdomains[a]!="undefined"&&typeof g_equivalentdomains[b]!="undefined"&&g_equivalentdomains[a]==g_equivalentdomains[b]?true:false}var LP=this;function mostRecent(){return window}function currentWindow(){return window}function en(a){return encodeURIComponent(a)}function lpprefsHasUserValue(a,b){return b}
function lpprefsGetBoolPref(a,b){return b}function lpprefsGetIntPref(a,b){return b}function lpGetAccounts(){get_accts()}function lpreadretry(){if(typeof localStorage=="undefined")return null;return localStorage.getItem(db_prepend(g_username_hash+".retry"))}function lpdeleteretry(){if(typeof localStorage=="undefined")return null;localStorage.removeItem(db_prepend(g_username_hash+".retry"))}
function lpwriteretry(a){if(g_username_hash==""||g_username_hash==null)return false;if(typeof localStorage=="undefined")return false;localStorage.setItem(db_prepend(g_username_hash+".retry"),a);return true}
function getuuid(){if(LPISLOC)return"";if(typeof localStorage=="undefined")return"";try{var a=localStorage.getItem(db_prepend("lp.uid"));if(a==null||a==""){if(g_is_win&&have_nplastpass()&&typeof g_nplastpass.read_file=="function"){a=g_nplastpass.read_file(db_prepend("lp.suid"));if(a==null||a==""){a=g_nplastpass.read_file(db_prepend("lp.uid"));if(a!=null&&a!=""){var b=protect_data(a,true);g_nplastpass.write_file(db_prepend("lp.suid"),b)}}else a=unprotect_data(a,true)}if(a==null||a==""){a=lpCreatePass(32,
1,1,1,1,1,1,1);localStorage.setItem(db_prepend("lp.uid"),a);if(g_is_win&&have_nplastpass()&&typeof g_nplastpass.write_file=="function"){b=protect_data(a,true);g_nplastpass.write_file(db_prepend("lp.suid"),b)}}}return a}catch(c){console_log("Error in getuuid: "+c);return""}}function lpdbg(a,b){console_log(b)}var lperrorcount=0;
function lpReportError(a){a=a;if(g_prompts.improve!=false){lperrorcount++;if(!(lperrorcount>100)){var b=a.match(/^(.*)location:\s+/);if(b)a=b[1];a="msg=cr() lp("+lpversion+") errors("+lperrorcount+"): "+LP.en(a);lpMakeRequest(base_url+"error.php?",a,null,null)}}}function lplog(a){console_log(a)}function lpatob(a){return atob(a)}function lpbtoa(a){return btoa(a)}function lpGetCurrentWindow(){return window}function bin2hex(a){return AES.bin2hex(a)}function hex2bin(a){return AES.hex2bin(a)}
function lp_hex2bin(a){return AES.hex2bin(a)}var lastopenauthwin=0;function ismultifactortaburl(a){return a.indexOf("browseraction=1&yubikey=1")!=-1||a.indexOf("browseraction=1&sesame=1")!=-1||a.indexOf("browseraction=1&grid=1")!=-1?true:false}
function openURL(a,b,c,d){get_selected_tab(null,function(g){g_selectedtabid=gettabid(g);g_selectedtab=g});a.indexOf("sesameusername")>0&&get_all_windows({populate:true},function(g){for(var h=g.length-1;h>=0;--h)for(var k=get_tabs_length(g[h])-1;k>=0;--k){var j=g[h].tabs[k].url;j&&lp_url_is_lastpassext(j)&&close_tab(g[h].tabs[k])}});var e=false;if(ismultifactortaburl(a))lastopenauthwin=(new Date).getTime();else if(a.indexOf("homelocal.html")!=-1)if((new Date).getTime()-1E3<lastopenauthwin)e=true;b||
(b=function(){});var f=lpGetPref("openpref","tabs");if(f=="same"&&(d||a.indexOf("-extension://")==6))f="tabs";if(f=="same")if(g_ischrome)get_selected_tab(null,function(g){if(g.url.match(/^https?:\/\/.*\//)){sendCS(g.id,{cmd:"loadurl",url:a});b(g,c)}else chrome.tabs.create({url:a},function(h){b(h,c)})});else if(g_issafari){e=safari.application.activeBrowserWindow.activeTab;b(e,c);e.url=a}else{if(g_isopera)if(e=opera.extension.tabs.getFocused()){b(e,c);e.update({url:a})}else{e=opera.extension.tabs.create({focused:true,
url:a});b(e,c)}}else if(f=="windows")if(g_ischrome)chrome.windows.create({url:a},function(g){b(g,c)});else if(g_issafari){e=safari.application.openBrowserWindow().activeTab;b(e,c);e.url=a}else{if(g_isopera){e=opera.extension.windows.create({focused:true,url:a});b(e,c)}}else{d=e?false:true;if(g_ischrome)chrome.tabs.create({url:a,selected:d},function(g){b(g,c)});else if(g_issafari){e=safari.application.activeBrowserWindow.openTab(e?"background":"foreground");b(e,c);e.url=a}else if(g_isopera){e=opera.extension.tabs.create({focused:true,
url:a});b(e,c)}}}function copyusername(a){Clipboard.copy(getusernamefromacct(g_sites[a]))}function copypassword(a,b){var c=g_sites[a];if(c.sharedfromaid!=null&&c.sharedfromaid!=""&&c.sharedfromaid!="0"&&c.sharedfromaid!="null")alert(gs("This is a shared site. You are not permitted to view the password."));else!b&&(c.pwprotect||g_prompts.view_pw_prompt)?security_prompt(function(){copypassword(a,true)}):Clipboard.copy(getpasswordfromacct(c))}
function refresh_windows(){get_all_windows({populate:true},function(a){for(var b=0;b<a.length;b++)for(var c=0;c<get_tabs_length(a[b]);c++)if(lp_url_is_lastpass(a[b].tabs[c].url)&&a[b].tabs[c].url.indexOf("lpnorefresh=1")==-1){var d=a[b].tabs[c].url;d=d.replace("&nk=1","");sendCS(gettabid(a[b].tabs[c]),{cmd:"loadurl",url:d})}})}
function closeallnotifications(){get_all_windows({populate:true},function(a){for(var b=0;b<a.length;b++)for(var c=0;c<get_tabs_length(a[b]);c++)sendCS(gettabid(a[b].tabs[c]),{cmd:"closenotification"})})}function recheckall(){get_all_windows({populate:true},function(a){for(var b=0;b<a.length;b++)for(var c=0;c<get_tabs_length(a[b]);c++)sendCS(gettabid(a[b].tabs[c]),{cmd:"recheck"},"all")});setprefs("all","all")}
function closecurrenttab(a){get_selected_tab(null,function(b){a!=""&&b.url.indexOf(a)==-1||close_tab(b)});select_selectedtabid()}function fill_default_ffid(){var a=lpGetPref("defaultffid","0");if(check_ident_ffid(a))for(var b=0;b<g_formfills.length;b++)if(g_formfills[b].ffid==a){fillform(a);return}confirm(gs("You have not yet chosen a default form fill profile.  Would you like to choose one now?"))&&openprefs()}
function setprefs(a,b){var c=getInt(lpGetPref("highlightFields",1)),d=getInt(lpGetPref("warninsecureforms",0)),e=getInt(lpGetPref("dontfillautocompleteoff",0)),f=getInt(lpGetPref("donotoverwritefilledfields",0)),g=getInt(lpGetPref("showGenerateNotifications",1)),h=getInt(lpGetPref("showFormFillNotifications",1)),k=getInt(lpGetPref("showNotificationsAfterClick",1)),j=getInt(lpGetPref("alwayschooseprofilecc",0)),n=getInt(lpGetPref("automaticallyFill",1)),i={cmd:"setprefs",highlightFields:c,warninsecureforms:d,
dontfillautocompleteoff:e,donotoverwritefilledfields:f,showGenerateNotifications:g,showFormFillNotifications:h,showNotificationsAfterClick:k,alwayschooseprofilecc:j,automaticallyFill:n};for(c=0;c<g_lp_hotkeys.length;c++){d=g_lp_hotkeys[c];i[d+"KeyCode"]=lpGetPref(d+"KeyCode");i[d+"Mods"]=lpGetPref(d+"Mods")}a=="all"?get_all_windows({populate:true},function(l){for(var m=0;m<l.length;m++)for(var o=0;o<get_tabs_length(l[m]);o++)sendCS(gettabid(l[m].tabs[o]),i,"all")}):sendCS(a,i,b)}
function get_registry_value(a,b,c){var d=c;if(g_is_win&&have_nplastpass()&&typeof g_nplastpass.get_registry_value=="function"){d=g_nplastpass.get_registry_value(a,b,c);if(typeof d!="string")d=c}return d}function gotourl(a){var b=null;if(g_sites[a])b=g_sites[a];else if(g_securenotes[a])return editAid(a);else return;a=b.url;a.match(/^[a-z]+?\:\/\//i)||(a="http://"+a);openURL(a)}
function deleteNever(a){for(var b=[],c=0;g_neverurls[a.type]&&c<g_neverurls[a.type].length;c++){var d=g_neverurls[a.type][c];d!=a.url&&b.push(d)}g_neverurls[a.type]=b;g_local_accts_version++;rewritelocalfile();b=0;switch(a.type){case "nevergenerates":b=1;break;case "neverformfills":b=2;break;case "neverautologins":b=3}a="delete=1&type="+LP.en(b)+"&url="+LP.en(a.url);lpMakeRequest(base_url+"add_never.php",a,function(){},function(){},null)}function db_prepend(a){if(LPISLOC)a="local_"+a;return a}
function changemasterpassword(){LPISLOC?openURL(getchromeurl("changemasterpw.html")):openbaseurl("?ac=1&opensettings=1")}
function change_master_password(a,b,c){var d=make_lp_key(a,b),e=[],f=[],g=[];if(!getBG().reencrypt(e,getBG().g_sites,d)||!getBG().reencrypt(f,getBG().g_securenotes,d)||!getBG().reencrypt(g,getBG().g_formfills,d))alert(gs("An error occurred"));else if(c){b=getBG().g_local_key;getBG().g_local_key=d;a=flattendata(g_local_accts_version+1,e,f,g_prompts,g,g_identities,g_equivalentdomains,g_neverurls,g_premium_exp,lpenc(a),g_pendings,g_shareeautopushes,lpmaxid,g_urlrules,g_prefoverrides);getBG().g_local_key=
b;return a}else{getBG().g_sites=e;getBG().g_securenotes=f;getBG().g_formfills=g;getBG().g_local_accts_version++;getBG().g_local_hash=make_lp_hash(a,b);getBG().g_local_key=make_lp_key(a,b);getBG().g_username=a;getBG().g_username_hash=SHA256(a);getBG().rewritelocalfile(false,true);getBG().g_pwdeckey=getBG().g_local_key;getBG().lpWriteKeyFile();getBG().lpnp_notify("local_pwchange",{data0:g_username,data1:b});alert(gs("Password updated!"));getBG().closecurrenttab("")}}
function reencrypt(a,b,c){for(var d in b){var e=[];if(!reencryptArray(e,b[d],c,false))return false;a[d]=e}return true}
var keystoreencrypt=["username","password","extra","profilename","firstname","middlename","lastname","email","company","ssn","birthday","address1","address2","city","state","state_name","zip","country","country_cc3l","country_name","mobilephone","mobilephone3lcc","mobileext","evephone","evephone3lcc","eveext","phone","phone3lcc","phoneext","fax","fax3lcc","faxext","ccnum","ccexp","cccsc","address3","title","gender","driverslicensenum","taxid","bankname","bankacctnum","bankroutingnum","timezone","county",
"ccstart","ccname","ccissuenum","notes","text","alttext","profilelanguage","lastname2","mobileemail","firstname2","firstname3","lastname3"];
function reencryptArray(a,b,c,d){try{for(var e in b)if(typeof b[e]=="object"){var f=[];if(!reencryptArray(f,b[e],c,e=="custom_fields"?2:d||e=="fields"))return false;a[e]=f}else if(lp_in_array(e,keystoreencrypt)||e=="value"&&(d==2||d&&fieldisencrypted(b))){var g=lpmdec(b[e],true);if((g==null||g=="")&&b[e]!=null&&b[e]!="")return false;var h=lpmenc(g,true,c);a[e]=h}else a[e]=b[e]}catch(k){console_error(k);return false}return true}
function fieldisencrypted(a){for(var b in a)if(b=="type"&&(a[b]=="password"||a[b]=="text"||a[b]=="hidden"||a[b]=="textarea"||"email"==a[b]))return true;return false}var lpclearrecent=false;function clearrecent(){if(typeof localStorage!="undefined"){localStorage.setItem(g_username_hash+"recent",lp_get_gmt_timestamp());lpclearrecent=true}}function getClearRecentTime(){if(typeof localStorage=="undefined")return 0;var a=localStorage.getItem(g_username_hash+"recent");if(a==null)return 0;return a}
function getRecentCount(){return lpGetPref("recentUsedCount",10)}function IsIconsUpdated(a){if(lpclearrecent){lpclearrecent=false;return true}return g_icons_length!=a}
function upgradetoserver(){confirm(gs("Please note that upgrading from LastPass Local to LastPass Online will result in your password data being uploaded in its encrypted format to LastPass servers.  You will be able to access your data from anywhere, and LastPass will not be able to read it.  Would you like to continue?"))&&security_prompt(function(){openURL(getchromeurl("welcome.html"))})}
function renameGroup(a,b){if(!(a==gs("favorites")||a==gs("recently usedlower"))){var c=[g_sites,g_securenotes],d;for(d in c){var e=c[d],f;for(f in e){var g=e[f];if(g.group==a)g.group=b}}g_local_accts_version++;rewritelocalfile();c="xml=1&origgrp="+LP.en(lpenc(a))+"&newgrp="+LP.en(lpenc(b));lpMakeRequest(base_url+"groups.php",c,function(){},function(){},null)}}function getacct(a){if(g_sites[a])return g_sites[a];else if(g_securenotes[a])return g_securenotes[a];return null}
function moveSelectedToGroup(a,b){var c=b.split(","),d=[],e=[];if(a==gs("favorites"))for(var f=0;f<c.length;f++){var g=getacct(c[f]);if(g&&g.fav=="0")d[d.length]=c[f]}if(c.length>0||d.length>0||e.length>0)changeGroupAndFavorites(c,d,e,a)}
function changeGroupAndFavorites(a,b,c,d){for(var e=c="",f="",g=0;g<a.length;g++){var h=a[g],k=getacct(h);if(k&&d!=gs("favorites")){k.group=d;c+=f+h;f=","}}f="";for(g=0;g<b.length;g++){h=b[g];if(k=getacct(h)){k.fav="1";e+=f+h;f=","}}g_local_accts_version++;g_server_accts_version++;rewritelocalfile();a="aids="+LP.en(c)+"&newfavaids="+LP.en(e)+"&oldfavaids="+LP.en("")+"&newgrp="+LP.en(lpenc(d))+"&xml=1";lpMakeRequest(base_url+"groups.php",a,lpChangeGroupResponse)}function lpChangeGroupResponse(){}
function lpReadFile(a){return have_nplastpass()&&typeof g_nplastpass.read_file=="function"?g_nplastpass.read_file(a):""}function is_chrome_portable(){return have_nplastpass()&&typeof g_nplastpass.is_chrome_portable=="function"&&g_nplastpass.is_chrome_portable()}
function doexport(a){if(lpGetPref("noexport",0)==1)alert(gs("CompanyPolicyProhibits"));else{if(!g_generatedpw)if(!a){security_prompt(function(){doexport(true)});return}g_export_output="url,username,password,extra,name,grouping,fav\n";a=[];for(var b in g_sites)if(check_ident_aid(b))if(g_sites[b].url!="http://group")a[a.length]=g_sites[b];for(b in g_securenotes)if(check_ident_aid(b))a[a.length]=g_securenotes[b];for(b=0;b<a.length;b++){var c=a[b];if(!(c.sharedfromaid!=null&&c.sharedfromaid!=""&&c.sharedfromaid!=
"0")){var d=[];d[0]=c.url;d[1]=getusernamefromacct(c);d[2]=getpasswordfromacct(c);d[3]=lpmdec(c.extra,true);d[4]=c.name;d[5]=c.group;d[6]=c.fav;for(var e=c="",f=0;f<d.length;f++){var g=d[f];if(g.match(/,|\r|\n|"/))g='"'+g.replace(/"/g,'""')+'"';c+=e+g;e=","}c+="\n";g_export_output+=c}}openURL(getchromeurl("export.html"))}}function fix_tlds(a,b,c){delete g_tlds[a][c];if(typeof g_tlds[b]=="undefined")g_tlds[b]=[];g_tlds[b][c]=true}function increment_local_accts_version(){g_local_accts_version++}
function set_editfieldsopener(a){g_editfieldsopener=a}function close_editfieldsopener(){if(g_editfieldsopener){g_editfieldsopener.close();g_editfieldsopener=null}}function getcurrenturl(){if(g_ischrome)return g_currenturl;else if(g_issafari)return safari.application.activeBrowserWindow.activeTab.url;else if(g_isopera)return opera.extension.tabs.getFocused()?opera.extension.tabs.getFocused().url:""}
function getcurrenttabid(){return g_ischrome?g_currenttabid:g_issafari?gettabid(safari.application.activeBrowserWindow.activeTab):gettabid(opera.extension.tabs.getFocused())}
function getsinglefactortype(){var a="";if(have_nplastpass()&&typeof g_nplastpass.read_file=="function")a=lptrim(g_nplastpass.read_file("singlefactortype"));var b=lpGetPref("singlefactortype","");if(a!=b){if(!have_nplastpass()||typeof g_nplastpass.file_exists!="function"||!g_nplastpass.file_exists("singlefactortype"))a=b;setsinglefactortype(a)}return a}
function setsinglefactortype(a){have_nplastpass()&&typeof g_nplastpass.write_file=="function"&&g_nplastpass.write_file("singlefactortype",a);getBG().lpPutGblPref("singlefactortype",a);a!=""&&getBG().lpPutGblPref("openloginstart",1);getBG().lpWriteAllPrefs()}function get_method(){if(g_ischrome)return"cr";else if(g_issafari)return"sfjs";else if(g_isopera)return"op"}
function select_selectedtabid(){try{if(g_ischrome)g_selectedtabid!=-1&&chrome.tabs.update(g_selectedtabid,{selected:true});else if(g_issafari)g_selectedtab&&g_selectedtab.activate();else g_isopera&&tab.update({focused:true})}catch(a){}}
function addEmptyGroup(a){var b=createNewAcct();b.url="http://group";b.group=a;b.aid="0";a="ajax=1&extjs=1&name=&url="+LP.en(bin2hex(b.url))+"&grouping="+LP.en(lpenc(b.group))+"&username=&password=&extra=&aid=0&openid_url=&isbookmark=0";lpMakeRequest(base_url+"show.php",a,lpSaveSiteResponse,null,b)}function hassites(){for(var a in g_sites)return true;for(a in g_securenotes)return true;return false}var g_basicauth_found=false,g_basicauth_url="",g_basicauth_realm="";
function basicauth_found(a,b,c){if(a!=g_basicauth_found)(g_basicauth_found=a)&&get_selected_tab(null,function(d){if(lp_gettld_url(c)!=lp_gettld_url(d.url))g_basicauth_found=false;else{g_basicauth_url=d.url;g_basicauth_realm=b;handleFill(gettabid(d),{url:d.url,topurl:d.url,docid:0,force:false,docnum:0})}})}
function cm_handler(a){console_log("******Context menu item is clicked****");console_log("menuItemId: "+a.menuItemId);console_log("parentMenuItemId: "+a.parentMenuItemId);console_log("mediaType: "+a.mediaType);console_log("linkUrl: "+a.linkUrl);console_log("srcUrl: "+a.srcUrl);console_log("pageUrl: "+a.pageUrl);console_log("frameUrl: "+a.frameUrl);console_log("selectionText: "+a.selectionText);console_log("editable  "+a.editable);lploggedin||openURL(getchromeurl("login.html"))}
function cm_callback(){console_log("Context menu callback function called")}function DeleteOldDynamicFiles(){var a=localStorage.getItem("ff.dat");if(a!=null){var b=a.indexOf("\n");if(b!=-1){a=a.substr(0,b);CompareLastPassVersions(ffver,a)>0&&localStorage.removeItem("ff.dat")}}}function geteventtargeturl(a){return g_isopera?a.message.topurl:a.target.url}function geteventtarget(a){return g_isopera?a.source:a.target}
function GetStringResource(a){if(have_nplastpass()&&typeof g_nplastpass.GetStringResource=="function")return g_nplastpass.GetStringResource("",a);return""}function GetImageResource(a){if(have_nplastpass()&&typeof g_nplastpass.GetImageResource=="function")return"data:image/png;base64,"+g_nplastpass.GetImageResource("",a);return""}function event_dispatch_message(a,b,c){if(g_issafari)geteventtarget(a).page.dispatchMessage(b,c);else if(g_isopera){c.messagetype=b;geteventtarget(a).postMessage(c)}}
function gettabidfromevent(a){if(g_isopera){for(var b=opera.extension.windows.getAll(),c=0;c<b.length;c++)for(var d=0;d<get_tabs_length(b[c]);d++)if(a.data.topurl==b[c].tabs[d].url)return gettabid(b[c].tabs[d]);return-1}else return gettabid(geteventtarget(a))}function LoadSpecialSites(){SpecialSites=[];var a=localStorage.getItem("sites.dat");if(a!=null&&a!=""){a=a.split("\n");for(var b=0;b<a.length;b++)if(a[b].indexOf(".")!=-1)SpecialSites[a[b]]=""}}function copytoclipboard(a){Clipboard.copy(a)};
