var KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,ELEMENT_NODE=1,KEY_ESCAPE=27,KEY_F4=115;function openCombo(a,d,b){a=document.getElementById(d);if(!a.disabled){b=gComboEx=document.getElementById(b);b.style.display=="block"?setStyle(b,"display","none",""):showCombo(a,b);gItemNum=-1;gFocusItem=a;setTimeout("doFocus();",0)}}
function showCombo(a,d){var b=0,c=0,e=a;do{if(e.style.position!="absolute"){b+=e.offsetTop;c+=e.offsetLeft}e=e.offsetParent}while(e);c=c+"px";setStyle(d,"top",b+a.offsetHeight+"px","");setStyle(d,"left",c,"");setStyle(d,"display","block","")}var gItemNum=0,gComboEx=null;
function focusCombo(a,d,b){a=a.keyCode;var c=true;b=gComboEx=document.getElementById(b);if(a==KEY_DOWN||a==KEY_F4){b.getAttribute("style.display")=="block"||showCombo(d,b);d=b.childNodes;b=d.length;for(a=0;d[a]!=null&&a<b;){if(d[a].nodeType==ELEMENT_NODE&&d[a].className=="item"){gFocusItem=d[a];break}a++}gItemNum=0;setTimeout("doFocus();",0);c=false}else if(a!=KEY_ENTER)if(a==KEY_ESCAPE)if(d.val!=null&&d.val.length>0)c=true;else{c=false;setStyle(gComboEx,"display","none","");gItemNum=-1}return c}
function focusItem(a,d,b){a=b.val;for(var c=null,e=getItems(d),g=e.length,f=false,h=0;h<g;h++)if(e[h].hasChildNodes()&&e[h].firstChild.nodeValue==a){f=true;c=e[h];gItemNum=h;break}if(!f){c=addItem(d,a,e.length);gItemNum=e.length}if(c!=null){gFocusItem=c;if(gComboEx.getAttribute("style.display")!="block"){a=b.offsetLeft+"px";setStyle(d,"top",b.offsetTop+b.offsetHeight+"px","");setStyle(d,"left",a,"")}else setStyle(d,"display","none","");setStyle(d,"display","block","");setTimeout("doFocus();",0)}}
function addItem(a,d,b){var c=document.createElement("div"),e=typeof d.label!="undefined"?d.label:d;c.val=typeof d.label!="undefined"?d.value:d;c.label=e;if(typeof d.label!="undefined"){c.label=d.label;if(typeof d.image!="undefined"){var g=document.createElement("img");g.src=d.image;g.style.paddingRight="15px";c.appendChild(g);c.img=g.src}}d=document.createTextNode(e);c.appendChild(d);c.setAttribute("tabindex","-1");c.setAttribute("class","item");c.setAttribute("onclick","gItemNum="+b+";");c.setAttribute("onmouseover",
"gFocusItem = this; doFocus();");c.setAttribute("role","listitem");c.style.overflow="hidden";a.appendChild(c);return c}
function doComboNav(a,d,b){var c=a.keyCode,e=true;if(gComboEx==null)gComboEx=d;if(c==KEY_UP||c==KEY_DOWN){e=false;a=0;d=getItems(gComboEx);var g=d.length;if(c==KEY_UP)a=gItemNum-1;else{a=gItemNum+1;if(a==g)a=-1}gItemNum=a;gFocusItem=gItemNum==-1?document.getElementById(b):d[a];setTimeout("doFocus();",0)}else if(c==KEY_ENTER||!a.keyCode&&a.button>=0){d=getItems(gComboEx);c=d[gItemNum];if(c!=null&&c.getAttribute("aria-disabled")!="true"){a=c.label;d=c.val;b=document.getElementById(b);b.value=a;b.val=
d;if(typeof c.img!="undefined"){b.style.background="url("+c.img+") no-repeat 2px 5px";b.style.paddingLeft="25px"}b.onchange&&b.onchange();setStyle(gComboEx,"display","none","");gItemNum=0;gFocusItem=b;setTimeout("doFocus();",0)}}else if(c==KEY_ESCAPE){e=false;setStyle(d,"display","none","");gItemNum=0;gFocusItem=document.getElementById(b);setTimeout("doFocus();",0)}return e}
function getItems(a){var d=[];d=[];a=a.childNodes;for(var b=a.length,c=0;c<b;c++)if(a[c].nodeType==ELEMENT_NODE&&(a[c].getAttribute("class")=="item"||a[c].getAttribute("class")=="item focus"))d[d.length]=a[c];return d}function setStyle(a,d,b,c){var e=false;try{if(a.style&&a.style.setProperty){a.style.setProperty(d,b,c);e=true}}catch(g){alert("exception caught setting style: "+g.message)}if(!e)try{a.style[d]=b;e=true}catch(f){alert("exception caught setting direct style: "+f.message)}return e}
gLastFocusItem=gFocusItem=null;function doFocus(){if(gFocusItem!=null){gFocusItem.focus();if(gLastFocusItem&&gLastFocusItem.className=="item focus")gLastFocusItem.className="item";if(gFocusItem&&gFocusItem.className=="item")gFocusItem.className="item focus";gLastFocusItem=gFocusItem;gFocusItem=null}}
function create_combo(a,d){var b=document.getElementById(a),c=a+"_combo";if(!document.getElementById(c)){b.setAttribute("onkeydown","return focusCombo(event, this, '"+c+"');");b.setAttribute("role","textfield");b.setAttribute("aria-haspopup","true");b.setAttribute("autocomplete","off");b.style.marginRight="0px";var e=b.style.width.replace(/px/,"");if(e=="")try{e=b.ownerDocument.defaultView.getComputedStyle(b,"").width.replace(/px/,"")}catch(g){}var f=document.createElement("div");f.setAttribute("role",
"list");f.setAttribute("style","display: none;");f.setAttribute("id",c);f.setAttribute("class","dropStyle");f.setAttribute("onkeydown","return doComboNav(event, this, '"+a+"');");f.setAttribute("onclick","doComboNav(event, this, '"+a+"');");f.style.width=parseInt(e)+4+"px";f.style.paddingLeft="6px";f.style.paddingRight="6px";b.nextSibling?b.parentNode.insertBefore(f,b.nextSibling):b.parentNode.appendChild(f);window.addEventListener("click",function(){close_combo(a)},false);for(e=0;e<d.length;e++)addItem(f,
d[e],e);e=document.createElement("img");e.setAttribute("onclick","openCombo(event, '"+a+"', '"+c+"'); event.cancelBubble = true;");e.setAttribute("src","dropdown.png");e.setAttribute("valign","middle");typeof g_isopera!="undefined"&&g_isopera&&e.setAttribute("style","position: relative; top: 7px;");b.parentNode.insertBefore(e,f)}}
function delete_combo_item(a,d){var b=document.getElementById(a+"_combo");if(b)for(var c=getItems(b),e=0;e<c.length;e++)if(c[e].innerHTML==d){for(c.splice(e,1);b.hasChildNodes();)b.removeChild(b.firstChild);for(e=0;e<c.length;e++)addItem(b,c[e].innerHTML,e);break}}function close_combo(a){if(a=document.getElementById(a+"_combo"))if(a.style.display=="block"){setStyle(a,"display","none","");gItemNum=-1}}
function repopulate_combo(a,d){var b=document.getElementById(a+"_combo");if(b){for(;b.hasChildNodes();)b.removeChild(b.firstChild);for(var c=0;c<d.length;c++)addItem(b,d[c],c)}};
