var g_ischrome=typeof chrome!="undefined"&&typeof chrome.extension!="undefined",g_issafari=typeof safari!="undefined"&&typeof safari.self!="undefined",lpParseUriCache=[],lpParseUriNumber=0;
function lpParseUri(a){if(typeof a!="string")return"";if(lpParseUriCache[a]!=null)return lpParseUriCache[a];var f=null,b=null,c=a;if(a.indexOf("#")!=-1){b=a.substring(a.indexOf("#")+1);a=a.substring(0,a.indexOf("#"))}if(a.indexOf("?")!=-1){f=a.substring(a.indexOf("?")+1);a=a.substring(0,a.indexOf("?"))}var d=a.match(/^(.*:\/\/[^\/]+\/.*)@/);if(d)a=a.substring(0,d[1].length)+a.substring(d[1].length).replace(/@/g,"%40");if(a.length>2047)return"";var g=lpParseUri.options;a=g.parser[g.strictMode?"strict":
"loose"].exec(a);var e={};for(d=14;d--;)e[g.key[d]]=a[d]||"";e[g.q.name]={};e[g.key[12]].replace(g.q.parser,function(j,i,k){if(i)e[g.q.name][i]=k});if(f!=null){e.query=f;if(b!=null)e.anchor=b}if(lpParseUriNumber>500){for(var h in lpParseUriCache){delete lpParseUriCache[h];break}lpParseUriNumber=0}lpParseUriCache[c]=e;lpParseUriNumber++;return e}
lpParseUri.options={strictMode:false,key:["source","protocol","authority","userInfo","user","password","host","port","relative","path","directory","file","query","anchor"],q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
function lp_gettld(a,f){if(typeof lp_all_tlds=="undefined"||lp_all_tlds==null)lp_init_tlds();if(typeof a!="string")return"";if(a==""&&typeof f=="string"&&f.indexOf("file://")==0)return"file:";a=a.toLowerCase();a=a.replace(/\.$/,"");var b=a.split("."),c;if(a.match(/^\d+\.\d+\.\d+\.\d+$/))c=4;else{c=2;if(b.length>=2){var d=b[b.length-1];if(typeof lp_all_tlds[d]!="undefined")if(lp_in_array(b[b.length-2],lp_all_tlds[d]))c=3}}for(;b.length>c;)b.shift();return b.join(".")}
function lp_init_tlds(){if(typeof lp_all_tlds=="undefined"||lp_all_tlds==null){lp_all_tlds=[];lp_all_tlds.hu=["2000","agrar","bolt","casino","city","co","com","erotica","erotika","film","forum","games","hotel","info","ingatlan","jogasz","konyvelo","lakas","media","news","nui","org","priv","reklam","sex","shop","sport","suli","szex","tm","tozsde","utazas","video"];lp_all_tlds.nl=["752"];lp_all_tlds.ca=["ab","bc","gc","mb","nb","nf","nl","ns","nt","nu","on","pe","qc","sk","yk"];lp_all_tlds.pa=["abo",
"ac","com","edu","gob","ing","med","net","nom","org","sld"];lp_all_tlds.se=["ab","ac","bd","brand","com","c","d","e","fh","fhsk","fhv","f","g","h","i","komforb","kommunalforbund","komvux","k","lanarb","lanbib","mil","m","naturbruksgymn","net","n","org","o","parti","pp","press","s","sshn","tm","t","u","w","x","y","z"];lp_all_tlds.ac=["ac","co","com","edu","gov","gv","mil","net","or","org"];lp_all_tlds.ae=["ac","com","gov","mil","name","net","org","pro","sch"];lp_all_tlds.at=["ac","co","gv","or","priv"];
lp_all_tlds.be=["ac","ap","co","com","fgov","to","xa"];lp_all_tlds.cn=["ac","ah","bj","com","cq","edu","fj","gd","gov","gs","gx","gz","ha","hb","he","hi","hk","hl","hn","jl","js","jx","ln","mo","net","nm","nx","org","qh","sc","sd","sh","sn","sx","tj","tw","xj","xz","yn","zj"];lp_all_tlds.cr=["ac","co","ed","fi","go","or","sa"];lp_all_tlds.cy=["ac","biz","com","ekloges","gov","info","ltd","name","net","org","parliament","press","pro","tm"];lp_all_tlds.fj=["ac","biz","com","gov","id","info","mil","name",
"net","org","pro","school"];lp_all_tlds.fk=["ac","co","gov","net","nom","org"];lp_all_tlds.gg=["ac","alderney","co","gov","guernsey","ind","ltd","net","org","sark","sch"];lp_all_tlds.gn=["ac","com","gov","net","org"];lp_all_tlds.gt=["com","edu","gob","ind","mil","net","org"];lp_all_tlds.id=["ac","co","go","mil","net","or","sch","web"];lp_all_tlds.il=["ac","co","gov","idf","k12","muni","net","org"];lp_all_tlds.im=["ac","co","gov","net","nic","org"];lp_all_tlds["in"]=["ac","co","edu","ernet","firm",
"gen","gov","ind","mil","net","nic","org","res"];lp_all_tlds.ir=["ac","co","gov","net","org","sch"];lp_all_tlds.is=["ac","org"];lp_all_tlds.je=["ac","co","gov","ind","jersey","ltd","net","org","sch"];lp_all_tlds.jp=["ac","ad","aichi","akita","aomori","chiba","co","ed","ehime","fukui","fukuoka","fukushima","gifu","go","gov","gr","gunma","hiroshima","hokkaido","hyogo","ibaraki","ishikawa","iwate","kagawa","kagoshima","kanagawa","kawasaki","kitakyushu","kobe","kochi","kumamoto","kyoto","lg","mie","miyagi",
"miyazaki","nagano","nagasaki","nagoya","nara","ne","net","niigata","oita","okayama","okinawa","org","or","osaka","saga","saitama","sapporo","sendai","shiga","shimane","shizuoka","tochigi","tokushima","tokyo","tottori","toyama","wakayama","yamagata","yamaguchi","yamanashi","yokohama"];lp_all_tlds.kr=["ac","co","go","ne","nm","or","re"];lp_all_tlds.mw=["ac","com","co","coop","edu","gov","int","museum","net","org"];lp_all_tlds.nz=["ac","co","cri","geek","gen","govt","iwi","maori","mil","net","org",
"school"];lp_all_tlds.ru=["ac","com","int","msk","net","org","pp"];lp_all_tlds.rw=["ac","com","co","edu","gouv","gov","int","mil","net"];lp_all_tlds.au=["act","asn","com","conf","csiro","edu","gov","id","info","net","nsw","nt","org","oz","qld","sa","tas","telememo","vic","wa"];lp_all_tlds.th=["ac","co","go","in","mi","net","or"];lp_all_tlds.tj=["ac","biz","com","co","edu","go","gov","int","mil","name","net","org","web"];lp_all_tlds.tz=["ac","co","go","ne","or"];lp_all_tlds.ug=["ac","co","go","ne",
"or","sc"];lp_all_tlds.uk=["ac","bl","british-library","com","co","gov","icnet","jet","ltd","me","mil","mod","national-library-scotland","nel","net","nhs","nic","nls","org","parliament","plc","police","sch"];lp_all_tlds.vn=["ac","biz","com","edu","gov","health","info","int","name","net","org","pro"];lp_all_tlds.yu=["ac","co","edu","org"];lp_all_tlds.za=["ac","alt","city","com","co","edu","gov","law","mil","net","ngo","nom","org","school","tm","web"];lp_all_tlds.zm=["ac","co","gov","org","sch"];lp_all_tlds.zw=
["ac","co","gov","org"];lp_all_tlds.br=["adm","adv","agr","am","arq","art","ato","bio","bmd","cim","cng","cnt","com","coop","dpn","ecn","edu","eng","esp","etc","eti","far","fm","fnd","fot","fst","g12","ggf","gov","imb","ind","inf","jor","lel","mat","med","mil","mus","net","nom","not","ntr","odo","org","ppg","pro","psc","psi","qsl","rec","slg","srv","tmp","trd","tur","tv","vet","zlg"];lp_all_tlds.ht=["adult","art","asso","com","coop","edu","firm","gouv","info","med","net","org","perso","pol","pro",
"rel","shop"];lp_all_tlds.mv=["aero","biz","com","coop","edu","gov","info","int","mil","museum","name","net","org","pro"];lp_all_tlds.pl=["agro","aid","art","atm","auto","bialystok","biz","com","edu","gdansk","gda","gmina","gov","gsm","info","krakow","lodz","lublin","mail","media","miasta","mil","net","ngo","nom","olsztyn","org","pc","poznan","priv","realestate","rel","shop","sklep","slupsk","sos","szczecin","targi","tm","torun","tourism","travel","turystyka","warszawa","waw","wroclaw","wroc"];lp_all_tlds.us=
["ak","al","ar","az","ca","com","co","ct","dc","de","dni","fed","fl","ga","hi","ia","id","il","in","isa","kids","ks","ky","la","ma","md","me","mi","mn","mo","ms","mt","nc","nd","ne","nh","nj","nm","nsn","nv","ny","oh","ok","or","pa","ri","sc","sd","tn","tx","ut","va","vt","wa","wi","wv","wy"];lp_all_tlds.fi=["aland"];lp_all_tlds.mil=["army","navy"];lp_all_tlds["do"]=["art","com","edu","gob","gov","mil","net","org","sld","web"];lp_all_tlds.dz=["art","asso","com","edu","gov","net","org","pol"];lp_all_tlds.co=
["arts","com","edu","firm","gov","info","int","mil","net","nom","org","rec","store","uk","web"];lp_all_tlds.ro=["arts","com","firm","info","nom","nt","org","rec","store","tm","www"];lp_all_tlds.ve=["arts","bib","com","co","edu","firm","gov","info","int","mil","net","nom","org","rec","store","tec","web"];lp_all_tlds.lv=["asn","com","conf","edu","eu","gov","id","mil","net","org"];lp_all_tlds.lk=["assn","com","edu","gov","grp","hotel","int","ltd","net","ngo","org","sch","soc","web"];lp_all_tlds.fr=["asso",
"com","gouv","nom","prd","presse","tm"];lp_all_tlds.gp=["asso","com","edu","net","org"];lp_all_tlds.mc=["asso","tm"];lp_all_tlds.tr=["av","bbs","bel","biz","com","dr","edu","gen","gov","info","k12","mil","name","net","org","pol","tel","web"];lp_all_tlds.az=["biz","com","edu","gov","info","int","mil","name","net","org","pp"];lp_all_tlds.et=["biz","com","edu","gov","info","name","net","org"];lp_all_tlds.nr=["biz","com","co","edu","gov","info","net","org"];lp_all_tlds.om=["biz","com","co","edu","gov",
"med","mil","museum","net","org","pro","sch"];lp_all_tlds.pk=["biz","com","edu","fam","gob","gok","gon","gop","gos","gov","net","org","web"];lp_all_tlds.pr=["biz","com","edu","gov","info","isla","name","net","org","pro"];lp_all_tlds.tt=["biz","com","co","edu","gov","info","name","net","org","pro","us"];lp_all_tlds.ua=["cherkassy","chernigov","chernovtsy","ck","cn","com","crimea","cv","dnepropetrovsk","dn","donetsk","dp","edu","gov","if","ivano-frankivsk","kharkov","kherson","khmelnitskiy","kh","kiev",
"kirovograd","km","kr","ks","kv","lg","lugansk","lutsk","lviv","mk","net","nikolaev","odessa","od","org","pl","poltava","rovno","rv","sebastopol","sumy","ternopil","te","uzhgorod","vinnica","vn","zaporizhzhe","zhitomir","zp","zt"];lp_all_tlds.tw=["club","com","ebiz","edu","game","gove","gov","idv","mil","net","org"];lp_all_tlds.ag=["co","com","net","nom","org"];lp_all_tlds.ao=["co","ed","gv","it","og","pb"];lp_all_tlds.bw=["co","org"];lp_all_tlds.ck=["co"];lp_all_tlds.ls=["co","org"];lp_all_tlds.ma=
["co","gov","net","org"];lp_all_tlds.af=["com","edu","gov","net"];lp_all_tlds.ai=["com","net","off","org"];lp_all_tlds.al=["com","edu","gov","inima","net","org","soros","tirana","uniti","upt"];lp_all_tlds.an=["com","edu","net","org"];lp_all_tlds.ar=["com","gov","int","mil","net","org"];lp_all_tlds.aw=["com"];lp_all_tlds.bb=["com","edu","gov","net","org"];lp_all_tlds.bd=["com","edu","gov","mil","net","org"];lp_all_tlds.bm=["com","edu","gov","net","org"];lp_all_tlds.bn=["com","edu","net","org"];lp_all_tlds.bo=
["com","edu","gob","gov","int","mil","net","org","tv"];lp_all_tlds.bs=["com","net","org"];lp_all_tlds.bt=["com","edu","gov","net","org"];lp_all_tlds.cd=["com","net","org"];lp_all_tlds.ch=["com","gov","net","org"];lp_all_tlds.cu=["com","edu","gov","inf","net","org"];lp_all_tlds.dm=["com","edu","gov","net","org"];lp_all_tlds.ec=["com","edu","fin","gov","info","k12","med","mil","net","org","pro"];lp_all_tlds.ee=["com","fie","org","pri"];lp_all_tlds.eg=["com","edu","eun","gov","mil","net","org","sci"];
lp_all_tlds.es=["com","edu","gob","nom","org"];lp_all_tlds.eu=["com"];lp_all_tlds.gb=["com","net"];lp_all_tlds.ge=["com","edu","gov","mil","net","org","pvt"];lp_all_tlds.gh=["com","edu","gov","mil","org"];lp_all_tlds.gi=["com","edu","gov","ltd","mod","org"];lp_all_tlds.gr=["com","edu","gov","net","org"];lp_all_tlds.gu=["com","edu","gov","mil","net","org"];lp_all_tlds.hk=["com","edu","gov","idv","net","org"];lp_all_tlds.hn=["com","edu","gob","mil","net","org"];lp_all_tlds.hr=["com","from","iz","name"];
lp_all_tlds.jm=["com","edu","gov","net","org"];lp_all_tlds.jo=["com","edu","gov","mil","net","org"];lp_all_tlds.kh=["com","edu","gov","mil","net","org","per"];lp_all_tlds.kw=["com","edu","gov","mil","net","org"];lp_all_tlds.ky=["com","edu","gov","net","org"];lp_all_tlds.kz=["com","edu","gov","mil","net","org"];lp_all_tlds.la=["com","net","org"];lp_all_tlds.lb=["com","edu","gov","mil","net","org"];lp_all_tlds.lc=["com","edu","gov","net","org"];lp_all_tlds.li=["com","gov","net","org"];lp_all_tlds.lr=
["com","edu","gov","net","org"];lp_all_tlds.ly=["com","edu","gov","id","med","net","org","plc","sch"];lp_all_tlds.mg=["com","edu","gov","mil","nom","org","prd","tm"];lp_all_tlds.mk=["com","org"];lp_all_tlds.mm=["com","edu","gov","net","org"];lp_all_tlds.mo=["com","edu","gov","net","org"];lp_all_tlds.mt=["com","edu","gov","net","org"];lp_all_tlds.mu=["com","co"];lp_all_tlds.mx=["com","edu","gob","gov","net","org"];lp_all_tlds.my=["com","edu","gov","mil","name","net","org"];lp_all_tlds.na=["com","net",
"org"];lp_all_tlds.nc=["com","net","org"];lp_all_tlds.ng=["com","edu","gov","net","org"];lp_all_tlds.ni=["com","edu","gob","net","nom","org"];lp_all_tlds.no=["com","fhs","folkebibl","fylkesbibl","herad","idrett","kommune","mil","museum","priv","stat","vgs"];lp_all_tlds.np=["com","edu","gov","mil","net","org","ort"];lp_all_tlds.pe=["com","edu","gob","mil","net","nom","org"];lp_all_tlds.pf=["com","edu","org"];lp_all_tlds.pg=["com","net"];lp_all_tlds.ph=["com","gov","mil","net","ngo","org"];lp_all_tlds.ps=
["com","edu","gov","net","org","plo","sec"];lp_all_tlds.pt=["com","edu","gov","int","net","nome","org","publ"];lp_all_tlds.py=["com","edu","gov","net","org"];lp_all_tlds.qc=["com"];lp_all_tlds.sa=["com","edu","gov","med","net","org","pub","sch"];lp_all_tlds.sb=["com","edu","gov","net"];lp_all_tlds.sc=["com","edu","gov","net","org"];lp_all_tlds.sd=["com","edu","gov","info","med","net","org","tv"];lp_all_tlds.sg=["com","edu","gov","idn","net","org","per"];lp_all_tlds.sh=["com","edu","gov","mil","net",
"org"];lp_all_tlds.sv=["com","co","edu","gob","org","red"];lp_all_tlds.sy=["com","gov","net","org"];lp_all_tlds.tn=["com","edunet","ens","fin","gov","ind","info","intl","nat","net","org","rnrt","rns","rnu","tourism"];lp_all_tlds.uy=["com","edu","gub","mil","net","org"];lp_all_tlds.vi=["com","co","edu","gov","net","org"];lp_all_tlds.ye=["com","net"];lp_all_tlds.pro=["cpa","law","med"];lp_all_tlds.arpa=["e164","in-addr","ip6","iris","uri","urn"];lp_all_tlds["int"]=["eu"];lp_all_tlds.bf=["gov"];lp_all_tlds.by=
["gov","mil"];lp_all_tlds.cx=["gov"];lp_all_tlds.ie=["gov"];lp_all_tlds.it=["gov","pisa"];lp_all_tlds.lt=["gov","mil"];lp_all_tlds.lu=["gov","mil","net","org"];lp_all_tlds.to=["gov"];lp_all_tlds.tp=["gov"];lp_all_tlds.tv=["gov"];lp_all_tlds.mobi=["music","weather"];lp_all_tlds.mh=["net"];lp_all_tlds.ad=["nom"];lp_all_tlds.sr=["rs"];lp_all_tlds.va=["vatican"]}}
function lpbeforeload(a){if(document.location.href.match(/lastpass.com/i)){var f=lpParseUri(document.location.href),b=f.file.toLowerCase();if(lp_gettld(f.host).toLowerCase()=="lastpass.com"){var c=lpParseUri(a.url).host.toLowerCase(),d=lp_gettld(c);if(f.host!="blog.lastpass.com")if(d!="lastpass.com"&&d!=""){var g=a.target.nodeName.toUpperCase(),e=a.url;if(!(e.indexOf("data:image/gif;base64,")==0||e.indexOf("data:image/png;base64,")==0||e.indexOf("about:blank")==0))if(!(b=="ads.php"&&d=="tradetracker.net"))if(!((b==
""||b=="index.php")&&f.query.toLowerCase().indexOf("securitychallenge")>=0&&c=="addtoany.simplecdn.net"))if(!(b=="news_latestnews.php"&&(d=="twimg.com"||c=="s3.amazonaws.com"||c=="static.twitter.com"||c="twitter.com")))if(!((b==""||b=="index.php"||b=="support_screencasts.php"||b=="misc_translate.php"||b=="basic.php")&&(d=="youtube.com"||d=="ytimg.com"||c=="www.google.com")))if(!(b=="debug.php"&&c=="rodan.lastpas.com"))if(!(b=="bwusage.php"&&c=="rtg.superb.net")){if(g=="IMG")if(c=="www.google-analytics.com"||
c=="ssl.google-analytics.com")return;console.error("BLOCKING "+a.url);a.preventDefault();a={cmd:"reporterror",e:"ERROR: CSP BLOCKING "+a.url};try{if(g_ischrome){var h=chrome.extension.connect({name:"blocked"});h&&h.postMessage(a)}else g_issafari&&safari.self.tab.dispatchMessage("message",a)}catch(j){}}}}}}document.location.href.match(/lastpass.com/i)&&document.addEventListener("beforeload",lpbeforeload,true);
