var g_maxchars=0,g_maxcharsmatch=0,g_menuwidth=0,g_menuwidthmatch=0,g_menus=[],g_menutitles=[],g_menuspeed=1E4,g_hoverrow=null,g_autoclickenabled=false;function onheightmenu(){return getBG().getmenuheight(true,true,true,g_browseraction)}function oninitmenu(){}function onshowmenu(){rebuildmenu();setTimeout("menuconnectevents()",100)}function onhidemenu(){$("#menu").html("")}
function getSiteMenuTitle(a,d){var b=d?getusernamefromacct(a):a.username,c=a.name+(b==""?"":" ("+b+")");if(c.length>g_maxcharsmatch){c=a.name;if(c.length>37)c=c.substring(0,40)+"...";if(b.length>=g_maxcharsmatch-c.length-3)b=b.substring(0,g_maxcharsmatch-c.length-3)+"...";c=c+(b==""?"":" ("+b+")")}return c}
function menuaction(a,d){L("TSM : menuaction cmd="+a);g_hoverrow=null;var b=getBG();if(b){var c="",g="",e="";if(a.indexOf("identity")==0&&a!="identityadd"){g=a.substring(8);if(g=="all")g="";a="identityswitch"}if(a.indexOf("matchopen")==0){c=a.substring(9);L("menuopen: "+c+" title: "+d);menuopen("match"+c,"match",d)}else if(a.indexOf("opendelete")==0){b=a.substring(10);menuopendelete(b,d)}else{if(a.indexOf("matchedit")==0){c=a.substring(9);a="matchedit"}else if(a.indexOf("matchfill")==0){c=a.substring(9);
a="matchfill"}else if(a.indexOf("matchcopyusername")==0){c=a.substring(17);a="matchcopyusername"}else if(a.indexOf("matchcopypassword")==0){c=a.substring(17);a="matchcopypassword"}else if(a.indexOf("matchdelete")==0){c=a.substring(11);a="matchdelete"}else if(a.indexOf("matchgotourl")==0){c=a.substring(12);a="matchgotourl"}if(a.indexOf("recentlyused")==0){c=a.substring(12);a=c=="clear"?"clearrecent":"site"}else if(a.indexOf("site")==0&&a!="siteadd"){c=a.substring(4);a="site"}else if(a.indexOf("note")==
0&&a!="noteadd"){c=a.substring(4);a="note"}else if(a.indexOf("fillforms")==0){e=a.substring(9);a="fillforms"}else if(a.indexOf("editprofile")==0){e=a.substring(11);a="editprofile"}switch(a){case "logoff":b.loggedOut(false,"menu");break;case "vault":b.openvault();break;case "openfavorites":b.openfavorites();break;case "preferences":b.openprefs();break;case "help":b.openhelp();break;case "premium":b.openpremium();break;case "server":b.upgradetoserver();break;case "saveall":b.saveall();break;case "tools":case "feedback":b.openfeedback();
break;case "generate":if(g_browseraction){hidemenu();openmole("lpgenerate");return}else b.opengenpw();break;case "search":b.opensearch();break;case "recheck":b.recheckpage();break;case "refresh":b.refreshsites();break;case "importgooglechrome":b.openimportchrome();break;case "lpimport":b.openimport();break;case "importfirefoxgo":break;case "importfirefoxhelp":break;case "import1passwordgo":break;case "import1passwordhelp":break;case "importkeepassgo":break;case "importkeepasshelp":break;case "importlastpassgo":break;
case "importlastpasshelp":break;case "importmsipasswordkeepergo":break;case "importmsipasswordkeeperhelp":break;case "importmypasswordsafego":break;case "importmypasswordsafehelp":break;case "importpasspackgo":break;case "importpasspackhelp":break;case "importpasswordagentgo":break;case "importpasswordagenthelp":break;case "importpasswordkeepergo":break;case "importpasswordkeeperhelp":break;case "importpasswordsafego":break;case "importpasswordsafehelp":break;case "importroboformgo":break;case "importroboformhelp":break;
case "importturbopasswordsgo":break;case "importturbopasswordshelp":break;case "importcsvgo":break;case "importcsvhelp":break;case "exportchrome":break;case "exportcsv":b.openexport();break;case "exportlastpass":b.openlastpassexport();break;case "printsites":b.openprint(false);break;case "printnotes":b.openprint(true);break;case "update":hidemenu();b.checkforupdates();if(g_isopera)break;else return;case "clear":b.clearCache(false);break;case "sessions":b.opensessions();break;case "seccheck":b.openseccheck();
break;case "about":b.openabout();break;case "addsite":b.openaddsite();break;case "addnote":b.openaddsecurenote();break;case "clearrecent":b.clearrecent();break;case "identityswitch":b.switch_identity(g);break;case "identityadd":b.add_identity();break;case "site":b.launch(c);break;case "siteadd":b.openaddsite();break;case "note":b.launch(c);break;case "noteadd":b.openaddsecurenote();break;case "fillforms":b.fillform(e);break;case "editprofile":b.editprofile(e);break;case "addprofile":b.addprofile();
break;case "addcreditcard":b.addcreditcard();break;case "clearforms":b.clearforms();break;case "chooseprofilecc":if(g_browseraction){hidemenu();openmole("lpchooseprofilecc");return}else b.openchooseprofilecc();break;case "matchedit":b.editAid(c);break;case "matchfill":b.fillaid(c);break;case "matchcopyusername":b.copyusername(c);break;case "matchcopypassword":b.copypassword(c);break;case "matchdelete":b.deleteAid(c,null);break;case "matchgotourl":b.gotourl(c,null);break;default:L("TSM : INVALID MENU ACTION cmd="+
a)}closemole()}}}function deletenever(a){a=getBG().getnevers()[a];getBG().deleteNever(a);closemole()}function rightclickmenuaction(a){var d="";if(a.indexOf("site")==0&&a!="siteadd"){d=a.substring(4);a="match_noautofill"+d}else if(a.indexOf("recentlyused")==0){d=a.substring(12);a="match_noautofill"+d}else if(a.indexOf("note")==0&&a!="noteadd"){d=a.substring(4);a="match_note"+d}else return true;menuopen(a,"match","");return false}
function getmenu(){var a=getBG(),d="";if(a.g_identity=="")d=gs("All");else for(var b in a.g_identities)if(a.g_identities[b].iid==a.g_identity){d=a.g_identities[b].deciname;break}var c={identityall:{title:gs("All")}};if(a.g_identity=="")c.identityall.icon="images/checkmark.gif";for(b in a.g_identities){c["identity"+a.g_identities[b].iid]={title:a.g_identities[b].deciname};if(a.g_identities[b].iid==a.g_identity)c["identity"+a.g_identities[b].iid].icon="images/checkmark.gif"}c.linebreak0=null;c.identityadd=
{title:gs("Add Identity")};var g={},e=a.lpGetPref("showAcctsInGroups",1)==1,h={},l,f,p=false,k=[],j=[],s=false;for(l in a.g_sites)if(a.check_ident_aid(l)){p=true;f=a.g_sites[l].group;if(f==null||f=="")f=gs("(none)");var n=f.split("\\"),i="";for(b=0;b<n.length;b++){if(b==0&&f[0]=="\\"){i+="\\";b++}else if(i!="")i+="\\";i+=n[b];lp_in_array(i,k)||(k[k.length]=i)}j[j.length]=a.g_sites[l];if(a.g_sites[l].fav=="1")s=true}k.sort(function(q,r){return q.toLowerCase()<r.toLowerCase()?-1:1});var m=e&&(s||k.length>
1);if(m&&s)h[gs("favorites")]={title:gs("favorites"),children:{}};var t=k.length;n=[];for(b=0;b<t;b++){f=k[b];var o=f.lastIndexOf("\\");i=o==-1||o==0?f:f.substring(o+1);i={title:i,children:{}};n[f]=i;if(o==-1||o==0){if(m)h[f+"sites"]=i}else n[f.substring(0,o)].children[f.replace(/\\/g,"~|~")+"sites"]=i}j.sort(function(q,r){return q.last_touch>r.last_touch?-1:1});f=a.getClearRecentTime();t=a.lpGetPref("recentUsedCount",10);for(b=0;b<j.length&&b<t;b++)j[b].last_touch<f||(g["recentlyused"+j[b].aid]=
{title:getSiteMenuTitle(j[b],true),icon:a.geticonurl(j[b].fiid,true)});if(array_length(g)==0)g.recentlyused0={title:gs("None Available")};else{g.linebreak0=null;g.recentlyusedclear={title:gs("Clear Recent")}}j.sort(function(q,r){return q.name.toLowerCase()<r.name.toLowerCase()?-1:1});for(b=0;b<j.length;b++){if(m&&j[b].fav=="1")if(typeof h[gs("favorites")]!="undefined")h[gs("favorites")].children["site"+j[b].aid]={title:getSiteMenuTitle(j[b],true),icon:a.geticonurl(j[b].fiid)};f=j[b].group;if(f==null||
f=="")f=gs("(none)");i={title:getSiteMenuTitle(j[b],true),icon:a.geticonurl(j[b].fiid)};if(m){if(typeof n[f]!="undefined")n[f].children["site"+j[b].aid]=i}else h["site"+j[b].aid]=i}if(p)h.linebreak0=null;h.siteadd={title:gs("Add Site")};j={};p=false;k=[];m=[];for(l in a.g_securenotes)if(a.check_ident_aid(l)){p=true;f=a.g_securenotes[l].group;if(f==null||f=="")f=gs("(none)");if(f!=gs("Secure Notes")){n=f.split("\\");i="";for(b=0;b<n.length;b++){if(i!="")i+="\\";i+=n[b];lp_in_array(i,k)||(k[k.length]=
i)}}m[m.length]=a.g_securenotes[l]}k.sort(function(q,r){return q.toLowerCase()<r.toLowerCase()?-1:1});e=e&&k.length>1;n=[];for(b=0;b<k.length;b++){f=k[b];o=f.lastIndexOf("\\");i=o==-1?f:f.substring(o+1);i={title:i,children:{}};n[f]=i;if(o==-1){if(e)j[f+"notes"]=i}else n[f.substring(0,o)].children[f.replace(/\\/g,"~|~")+"notes"]=i}m.sort(function(q,r){return q.name.toLowerCase()<r.name.toLowerCase()?-1:1});for(b=0;b<m.length;b++){f=m[b].group;if(f==null||f=="")f=gs("(none)");if(e&&f!=gs("Secure Notes"))n[f].children["note"+
m[b].aid]={title:m[b].name,icon:a.geticonurl(m[b].fiid)}}for(b=0;b<m.length;b++){f=m[b].group;if(!e||f==gs("Secure Notes"))j["note"+m[b].aid]={title:m[b].name,icon:a.geticonurl(m[b].fiid,true)}}if(p)j.linebreak0=null;j.noteadd={title:gs("Add Secure Note")};e={};f=l=p=false;for(b in a.g_formfills)if(a.check_ident_ffid(a.g_formfills[b].ffid)){p=true;e["fillforms"+a.g_formfills[b].ffid]={title:a.g_formfills[b].decprofilename};if(a.g_formfills[b].profiletype==0)l=true;if(a.g_formfills[b].ccnum!="")f=
true}if(p){e.linebreak0=null;e.editprofiles={title:gs("Edit"),children:{}};for(b in a.g_formfills)if(a.check_ident_ffid(a.g_formfills[b].ffid))e.editprofiles.children["editprofile"+a.g_formfills[b].ffid]={title:a.g_formfills[b].decprofilename}}e.addprofile={title:gs("Add Profile")};e.addcreditcard={title:gs("Add Credit Card")};e.clearforms={title:gs("Clear Forms")};if(l&&f)e.chooseprofilecc={title:gs("Choose Profile and Credit Card")};b=a.g_identity!=""?" ("+d+")":"";a={logoff:{icon:"images/power_off.png",
title:gs("Logoff:")+" "+a.g_username+b,cmd:"logoff"},linebreak1:null,vault:{icon:"images/icon_vault.png",title:gs("My LastPass Vault"),hotkey:"Ctrl+Alt+H",cmd:"vault"},recent:{icon:"images/icon_recent.png",title:gs("Recently Used"),children:g},sites:{icon:"images/icon_sites.png",title:gs("Sites"),children:h},notes:{icon:"images/icon_notes.png",title:gs("Secure Notes"),hidden:a.g_hidenotes,children:j},openfavorites:{icon:"images/icon_favorites.png",title:gs("Open Favorites"),cmd:"openfavorites",hidden:!s},
formfill:{icon:"images/icon_formfill.png",title:gs("Fill Forms"),children:e},preferences:{icon:"images/icon_preferences.png",title:gs("Preferences"),cmd:"preferences"},help:{icon:"images/icon_help.png",title:gs("Help..."),cmd:"help"},tools:{icon:"images/icon_tools.png",title:gs("Tools"),children:{generate:{icon:"images/keyboard.png",title:gs("Generate Secure Password"),key:"Alt+G"},identities:{icon:"images/icon_identities.png",title:gs("Identities")+" ("+d+")",hidden:a.g_hideidentities,children:c},
feedback:{icon:"images/up-red.gif",title:gs("Feedback")},search:{icon:"images/search-icon-blue.gif",title:gs("Site Search"),key:"Alt+W"},recheck:{icon:"images/page_gear.png",title:gs("Recheck Page"),key:"Alt+I"},refresh:{icon:"images/reload.gif",title:gs("Refresh Sites"),hidden:a.LPISLOC},lpimport:{icon:"images/import.png",title:gs("Import"),hidden:!g_isopera},importmenu:{icon:"images/import.png",title:gs("Import From"),hidden:a.g_hideimport||g_isopera,children:{importgooglechrome:{title:gs("Google Chrome Password Manager")},
lpimport:{title:gs("Other"),hidden:a.LPISLOC}}},lpexport:{icon:"images/export.png",title:gs("Export To"),hidden:a.g_hideexport,children:{exportcsv:{title:gs("LastPass CSV File")},exportlastpass:{title:gs("LastPass Encrypted File"),hidden:g_isopera}}},print:{icon:"images/printer.png",title:gs("Print"),hidden:a.g_hideprint,children:{printsites:{title:gs("Sites")},printnotes:{title:gs("Secure Notes")}}},update:{icon:"images/exclamation.png",title:gs("Check For Updates"),hidden:g_isopera},clear:{icon:"images/computer_delete.png",
title:gs("Clear Local Cache"),hidden:a.LPISLOC},seccheck:{icon:"images/tick.png",title:gs("Security Check"),hidden:a.LPISLOC},sessions:{icon:"images/group_key.png",title:gs("Other Sessions"),hidden:a.LPISLOC},about:{icon:"images/icon16.png",title:gs("About...")},linebreak0:null,addsite:{icon:"images/icon_saveall.png",title:gs("Add Site")},addnote:{icon:"images/note_add.png",title:gs("Add Secure Note"),hidden:a.g_hidenotes}}},linebreak2:null,premium:{icon:"images/icon_premium.png",title:gs("Go Premium!"),
cmd:"premium",hidden:a.LPISLOC},server:{icon:"images/icon_premium.png",title:gs("Upgrade to LastPass Online!"),cmd:"server",hidden:!a.LPISLOC},saveall:{icon:"images/icon_saveall.png",title:gs("Save All Entered Data"),cmd:"saveall"},matchscroll:null};0==t&&delete a.recent;return a}
function rebuildmenu(){var a=g_isopera?"overflow-x:hidden;min-width:3000px;":"";g_hoverrow=null;var d="";d+='<div id="menutitle" style="display:none;margin:0 5px 1px 5px;padding:0 5px;cursor:pointer;background:url(menuheader.png) repeat-x;color:#fff;text-align:center;height:20px;line-height:20px;vertical-align:middle;font-weight:bold;"></div>';d+='<div id="backbutton1" class="backbutton" style="display:none;margin:0px 5px;padding:0 5px;cursor:pointer;background:url(backbg.png) repeat-x;color:#fff;text-align:center;height:20px;line-height:20px;vertical-align:middle;font-weight:bold;"><img src="backarrow.png"/> BACK</div>';
d+='<table cellspacing="0"><tr>';d+='<td>&nbsp;<div id="menu0" style="overflow-y:auto;overflow-x:hidden;max-height:400px;"></div></td>';d+='<td>&nbsp;<div id="menu1" style="overflow-y:auto;overflow-x:hidden;max-height:400px;width:0px;display:none;"></div></td>';d+="</tr></table>";d+='<div id="backbutton2" class="backbutton" style="display:none;margin:10px 5px 0 5px;padding:0 5px;cursor:pointer;background:url(backbg.png) repeat-x;color:#fff;text-align:center;height:20px;line-height:20px;vertical-align:middle;font-weight:bold;"><img src="backarrow.png"/> BACK</div>';
$("#menucontainer").html(d);$(".backbutton").hover(function(){g_hoverrow=$(this).attr("id");setTimeout('menuautoclick("'+g_hoverrow+'")',1E3);$(this).css({background:"url(backbgover.png) repeat-x"})},function(){g_hoverrow=null;$(this).css({background:"url(backbg.png) repeat-x"})}).click(function(){popmenu()});var b=getmenu();g_maxchars=40;g_maxcharsmatch=33;g_menuwidth=9*g_maxchars;g_menuwidthmatch=9*g_maxcharsmatch;if(getBG().lpGetPref("language","en-US")=="en-US")g_maxcharsmatch=50;d="";var c,g,
e;for(c in b)if(c=="matchscroll"){e=getBG().getnevers();g=true;for(c in e){if(g){g=false;d+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>'}var h=gs("Never Add Site");if(e[c].type=="neverautologins")h=gs("Never AutoLogin");if(e[c].type=="nevergenerates")h=gs("Never Generate Password");if(e[c].type=="neverformfills")h=gs("Never Fill Forms");if(e[c].domain==1)h+=" "+gs("(domain)");d+='<div style="'+a+'">';d+='<div class="newmenurow" style="float:left;color:#000;padding:1px 5px;" onclick="menuaction(\''+
("opendelete"+c)+"','"+es(lpxmlescape(h))+"');\">";d+='<div style="min-height:16px;float:left;width:'+g_menuwidth+'px;cursor:pointer;overflow:hidden;background:url(close.png) no-repeat;padding-left:20px;padding-top:2px;">'+h+"</div>";d+='<img src="arrow.png">&nbsp;';d+="</div>";d+='<div style="clear:both;"></div>';d+="</div>"}e=getBG().getmatchingsites();if(e.length>0){d+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';for(c in e){g="match"+e[c].aid;h=getSiteMenuTitle(e[c],false);
d+='<div style="'+a+'">';d+='<div id="menurow'+es(lpxmlescape(g))+'" class="newmenurow" style="float:left;color:#000;padding:1px 5px;" onclick="menuaction(\''+("matchopen"+e[c].aid)+"','"+es(lpxmlescape(h))+"');\">";d+='<div style="min-height:16px;float:left;width:'+g_menuwidthmatch+"px;cursor:pointer;overflow:hidden;background:url("+getBG().geticonurl(e[c].fiid)+') no-repeat;padding-left:20px;padding-top:2px;">'+h+"</div>";d+='<img src="arrow.png" alt="expand"/>&nbsp;';d+='<div style="clear:both;"></div>';
d+="</div>";d+='<img src="fill.png" alt="autofill" style="cursor:pointer;" title="AutoFill" onclick="menuaction(\''+("matchfill"+e[c].aid)+"');\"/>&nbsp;";if(!g_isopera){d+='<img src="copyusername.png" alt="copyusername" style="cursor:pointer;" title="Copy Username" onclick="menuaction(\''+("matchcopyusername"+e[c].aid)+"');\"/>&nbsp;";d+='<img src="copypassword.png" alt="copypassword" style="cursor:pointer;" title="Copy Password" onclick="menuaction(\''+("matchcopypassword"+e[c].aid)+"');\"/>&nbsp;"}d+=
"&nbsp;&nbsp;&nbsp;&nbsp;";d+='<div style="clear:both;"></div>';d+="</div>"}}}else if(b[c]==null)d+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';else if(!(b[c].cmd=="premium"&&getBG().g_premium_exp>lp_get_local_timestamp())){h=b[c].title;if(h.length>g_maxchars)h=h.substring(0,g_maxchars-3)+"...";e="";if(typeof b[c].children!="undefined")e=" onclick=\"menuopen('"+es(lpxmlescape(c))+"',null,'"+es(lpxmlescape(h))+"')\"";else if(typeof b[c].cmd!="undefined")e=" onclick=\"menuaction('"+
es(b[c].cmd)+"')\"";g="";if(b[c].hidden)g="display: none;";d+='<div id="menurow'+es(lpxmlescape(c))+'" class="newmenurow" style="'+a+"color:#000;padding:1px 5px;"+g+'"'+e+">";d+='<div style="min-height:16px;float:left;width:'+g_menuwidth+"px;cursor:pointer;overflow:hidden;background:url("+b[c].icon+') no-repeat;padding-left:20px;padding-top:2px;">'+of(h)+"</div>";if(typeof b[c].children!="undefined")d+='<img src="arrow.png" alt="expand"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';d+='<div style="clear:both;"></div>';
d+="</div>"}d+="<div><br/><br/><br/></div>";pushmenu(d,"")}
function pushmenu(a,d){var b=$("#menu0"),c=$("#menu1"),g=c.width(),e=false;if(a){g_menus.push(a);if(g_menus.length==1){b.html(a);return}c.html(a)}var h=Math.abs(parseInt(b.css("margin-left").replace("px","")));if(h<g_menuwidth){h=h+g_menuspeed<g_menuwidth?h+g_menuspeed:g_menuwidth;b.css("margin-left",-h+"px");if(h==g_menuwidth)b.hide();else e=true}if(g_menus.length!=2)if(g<g_menuwidth){g==0&&c.show();g=g+g_menuspeed<g_menuwidth?g+g_menuspeed:g_menuwidth;c.width(g);e=true}if(e)setTimeout('pushmenu(null,"'+
es(d)+'")',0);else{b.html(c.html()).css("margin-left","0px");c.hide().html("").css("width","0px");b.show();setTimeout("menuconnectevents()",100);g_menutitles.push(d);$("#menutitle").html(of(d)).show();$(".backbutton").show()}}
function popmenu(a){var d=$("#menu0"),b=$("#menu1"),c=b.width(),g=false;if(!a){d.hide().html(g_menus[g_menus.length-2]).css("margin-left",g_menuwidth+"px");b.css("width",g_menuwidth+"px").html(g_menus[g_menus.length-1]).show();g_menus.pop();c=g_menuwidth}if(c>0){c=c-g_menuspeed>0?c-g_menuspeed:0;b.width(c);if(c==0)b.hide();else g=true}a=Math.abs(parseInt(d.css("margin-left").replace("px","")));a==g_menuwidth&&d.show();if(a>0){a=a-g_menuspeed>0?a-g_menuspeed:0;d.css("margin-left",-a+"px");g=true}if(g)setTimeout("popmenu(1)",
0);else{b.html("");setTimeout("menuconnectevents()",100);g_menutitles.pop();if(g_menus.length==1){$("#menutitle").hide().html("");$(".backbutton").hide()}else $("#menutitle").html(of(g_menutitles[g_menutitles.length-1]))}}
function menuconnectevents(){$(".newmenurow").hover(function(){g_hoverrow=$(this).attr("id");setTimeout('menuautoclick("'+g_hoverrow+'")',1E3);$(this).css({background:"#316AC5",color:"#fff"}).children("img").attr("src","arrowon.png")},function(){g_hoverrow=null;$(this).css({background:"#fff",color:"#000"}).children("img").attr("src","arrow.png")})}
function menuautoclick(a){if(g_autoclickenabled)if(a==g_hoverrow){g_hoverrow=null;if(a=="backbutton1"||a=="backbutton2")$("#"+a).click();else{var d=a.substring(7),b=d.indexOf("match")==0?"match":null;getmenuchildren(d,b)!=null&&$("#"+a).click()}}}
function menuopen(a,d,b){var c=g_isopera?"overflow-x:hidden;min-width:3000px;":"";L("menuopen cmd="+a+" menutitle="+b);d=getmenuchildren(a,d);if(d==null)L("No children for cmd="+a+" menutitle="+b);else{a="";var g,e,h,l;for(l in d){e=d[l];if(e==null)a+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';else{h=e.title;if(h.length>g_maxchars)h=h.substring(0,g_maxchars-3)+"...";g=typeof e.children!="undefined"?" onclick=\"menuopen('"+es(lpxmlescape(l))+"',null,'"+es(lpxmlescape(h))+"')\"":
" onclick=\"menuaction('"+es(lpxmlescape(l))+"','"+es(lpxmlescape(h))+"')\" onContextMenu=\"return rightclickmenuaction('"+es(l)+"')\"";bgicon=typeof e.icon!="undefined"?"background:url("+e.icon+") no-repeat;":"";var f="";if(e.hidden)f="display: none;";a+='<div id="menurow'+es(lpxmlescape(l))+'" class="newmenurow" style="'+c+"color:#000;padding:1px 5px;"+f+'"'+g+">";a+='<div style="min-height:16px;float:left;width:'+g_menuwidth+"px;cursor:pointer;overflow:hidden;"+bgicon+'padding-left:20px;padding-top:2px;">'+
lpxmlescape(h)+"</div>";if(typeof e.children!="undefined")a+='<img src="arrow.png" alt="expand"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';a+='<div style="clear:both;"></div>';a+="</div>"}}pushmenu(a,b)}}
function menuopendelete(a,d){var b="",c=gs("Delete"),g=" onclick=\"deletenever('"+es(a)+"')\"";b+='<div id="menurow'+es(a)+'" class="newmenurow" style="color:#000;padding:1px 5px;"'+g+">";b+='<div style="min-height:16px;float:left;width:'+g_menuwidth+'px;cursor:pointer;overflow:hidden;padding-left:20px;padding-top:2px;">'+lpxmlescape(c)+"</div>";b+='<div style="clear:both;"></div>';b+="</div>";pushmenu(b,d)}
function getmenuchildren(a,d){var b=null;if(d=="match"){b=findmatchmenuchildren(a);if(b!=null)return b}return findmenuchildren(a)}function findmenuchildren(a,d){var b,c=typeof d=="undefined"?getmenu():d,g;for(g in c){if(g==a)return c[g]==null||typeof c[g].children=="undefined"?null:c[g].children;if(c[g]!=null&&typeof c[g].children!="undefined"){b=findmenuchildren(a,c[g].children);if(b!=null)return b}}return null}
function findmatchmenuchildren(a){if(a.indexOf("match")!=0)return null;var d=true,b=true,c=true,g=false,e=null;if(a.indexOf("match_noautofill")==0){d=false;g=true;e=a.substring(16)}else if(a.indexOf("match_note")==0){c=b=d=false;g=true;e=a.substring(10)}else e=a.substring(5);a="matchedit"+e;var h="matchfill"+e,l="matchcopyusername"+e,f="matchcopypassword"+e,p="matchdelete"+e;e="matchgotourl"+e;var k={};if(g)k[a]={title:gs("Edit")};if(d)k[h]={title:gs("AutoFill")};if(b&&!g_isopera){k[l]={title:gs("Copy Username")};
k[f]={title:gs("Copy Password")}}g||(k[a]={title:gs("Edit")});if(c)k[e]={title:gs("Go to URL")};k[p]={title:gs("Delete")};return k};
