var g_np_init=false,namedpipeobserverfunction=null;
function lpnp_init(){if(!g_is_win&&!g_is_mac&&!g_is_linux){lpdbg("namedpipes","Linux is totally broken on named pipes, simply quit for now");g_np_init=false}else if(g_nplastpass)if(is_chrome_portable())g_np_init=false;else{lpdbg("namedpipes","lpnp_init : initializing named pipe server");namedpipeobserverfunction={observe:function(c,f,a){try{if(f=="lpxpcom"){c="";var e=a.match(/^<([^ \/]+)/);if(e)c=e[1];if(!(LPISLOC&&c!="refresh_local"&&c!="local_pwchange")){lpdbg("namedpipes","received cmd="+c+" data="+
a);switch(c){case "pipeinitdone":if(g_nplastpass.NamedPipeNumClients()>1){var d=[];lpnp_notify("internal_logincheck",d);setTimeout(function(){lp_StartLogin()},500)}else lp_StartLogin();break;case "logout":console_log("LOGGING OFF : namedpipes : logoff");lplogoff(true);break;case "login":var p=a.match(/data0=\"([^\"]*)\"/),g=a.match(/data1=\"([^\"]*)\"/);if(p&&g){var b=lpxmlunescape(p[1]),q=lpxmlunescape(g[1]);b!=""&&q!=""&&lp_loginhelper(b,q,"namedpipes")}break;case "refresh":refresh_windows();break;
case "switchidentity":if(g=a.match(/data0=\"([^\"]*)\"/)){var s=lpxmlunescape(g[1]);switch_identity(s,true,false,true)}break;case "launch":g=a.match(/id=\"([^\"]*)\"/);var t=a.match(/existing=\"([^\"]*)\"/);if(g){var l=lpxmlunescape(g[1]);d=[];d.data0=l;lpnp_notify("launchok",d);t?fillaid(l):launch(l)}break;case "internal_logincheck":if(lploggedin){d=[];d.data0=lp_phpsessid;d.data1=g_username;d.data2=g_identity;lpnp_notify("internal_logincheck_ack",d)}break;case "internal_logincheck_ack":var i=a.match(/data0=\"([^\"]*)\"/);
b=a.match(/data1=\"([^\"]*)\"/);var j=a.match(/data2=\"([^\"]*)\"/);if(!lploggedin&&i&&b){var h=opendb();createSavedLoginsTable(h);h&&h.transaction(function(m){var n=(new Date).getTime();m.executeSql("UPDATE LastPassSavedLogins2 SET last_login = ? WHERE username = ?",[n,lpxmlunescape(b[1])],function(k,o){o.rowsAffected==0&&k.executeSql("INSERT INTO LastPassSavedLogins2 (username, password, last_login) VALUES (?, '', ?)",[lpxmlunescape(b[1]),n])},function(k,o){console_log(o)})});e=g_username_hash;
d=g_username;g_username=lpxmlunescape(b[1]);g_username_hash=SHA256(lpxmlunescape(b[1]));g_identity=""+(j?lpxmlunescape(j[1]):"");lpPutUserPref("identity",j?lpxmlunescape(j[1]):"");g_username=d;g_username_hash=e;lpWriteAllPrefs();lp_phpsessid=lpxmlunescape(i[1]);rsa_setpendingsharests();if(have_nplastpass()&&typeof g_nplastpass.read_file=="function"){a=g_nplastpass.read_file(db_prepend(SHA256(lpxmlunescape(b[1]))+"_lpall.slps"));if(typeof a!="string"||a==""){a=g_nplastpass.read_file(db_prepend(SHA256(lpxmlunescape(b[1]))+
"_lpall.lps"));if(typeof a=="string"&&a!=""){var u=protect_data(a,true);g_nplastpass.write_file(db_prepend(SHA256(lpxmlunescape(b[1]))+"_lpall.slps"),u);g_nplastpass.delete_file(db_prepend(SHA256(lpxmlunescape(b[1]))+"_lpall.lps"))}}else a=unprotect_data(a,true);if(typeof a=="string"&&a!=""){h=opendb();createDataTable(h);h&&h.transaction(function(m){m.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, 'key', ?)",[db_prepend(SHA256(lpxmlunescape(b[1]))),a],function(){lp_StartLogin(true)},
function(n,k){console_log(k)})})}}}else if(lploggedin&&i&&b)if(lp_phpsessid!=lpxmlunescape(i[1])||g_username!=lpxmlunescape(b[1])){console_log("LOGGING OFF : namedpipes : different username");lplogoff()}break;case "refresh_local":var r=a.match(/data0=\"([^\"]*)\"/);r&&lpxmlunescape(r[1])==g_username_hash&&get_accts_local();break;case "local_pwchange":console_log("LOGGING OFF : namedpipes : local_pwchange");lplogoff();break;default:lpdbg("namedpipes","received unknown message. data="+a)}}}}catch(v){}}}.observe;
g_nplastpass.StartNamedPipeServer();g_np_init=true;setTimeout(function(){lpnp_notify("logincheck")},1E3)}else lpdbg("namedpipes","named pipe server could not be started g_nplastpass="+g_nplastpass)}function lpnp_notify(c,f){if(!(LPISLOC&&c!="refresh_local"&&c!="local_pwchange"))if(!(!g_nplastpass||!g_np_init||!have_nplastpass()||typeof g_nplastpass.SendNamedPipeMessageToAll!="function")){var a=lpnp_xml_msg(c,f);lpdbg("namedpipes","broadcasting "+a);g_nplastpass.SendNamedPipeMessageToAll(a)}}
function lpnp_xml_msg(c,f){var a="<"+c,e;if(typeof f!="undefined")for(e in f)a+=" "+e+'="'+lpxmlescape(f[e])+'"';a+="/>";return a};
