function lpPutUserPref(b,a){g_userprefs[b]=a}function lpPutGblPref(b,a){g_gblprefs[b]=a}function lpGetPref(b,a){if(typeof g_userprefs[b]!="undefined")return g_userprefs[b];if(typeof g_gblprefs[b]!="undefined")return g_gblprefs[b];return a}
function lpReadAllPrefs(b){lplog("PREFS:A");var a=g_username_hash&&g_username_hash!=""?g_username_hash:"";g_userprefs=[];g_identity="";var c=opendb();lplog("PREFS:B db="+c);createPrefsTable(c);lplog("PREFS:C");if(c){lplog("PREFS:D");c.transaction(function(f){lplog("PREFS:E");f.executeSql("SELECT * FROM LastPassPreferences where username_hash=? or username_hash=?",[a,""],function(d,e){lplog("PREFS:F rs="+e);lplog("PREFS:G rs.rows="+e.rows);lplog("PREFS:H rs.rows.length="+e.rows.length);g_gblprefs=
[];for(var g=0;g<e.rows.length;g++){var j=e.rows.item(g).username_hash,h=e.rows.item(g).prefname,i=e.rows.item(g).prefvalue;if(j!=""){if(h!="language"){g_userprefs[h]=i;if(h=="identity")g_identity=i}}else g_gblprefs[h]=i}if(g_issafari||g_isopera){g=lpGetPref("language","");include_language(g)}lplog("PREFS:I");start_idle_checker();lplog("PREFS:J");if(typeof g_gblprefs.generateHkKeyCode=="undefined"){lplog("PREFS:K");setup_default_hotkeys()}lplog("PREFS:L");console_log("read: "+e.rows.length+" preferences");
b&&b(e.rows.length)},function(d,e){console_log(e)})})}else b&&b()}
function setup_default_hotkeys(){if(g_is_mac){lpPutGblPref("generateHkKeyCode",0);lpPutGblPref("generateHkMods","");lpPutGblPref("recheckHkKeyCode",0);lpPutGblPref("recheckHkMods","");lpPutGblPref("searchHkKeyCode",0);lpPutGblPref("searchHkMods","");lpPutGblPref("nextHkKeyCode",33);lpPutGblPref("nextHkMods","meta");lpPutGblPref("prevHkKeyCode",34);lpPutGblPref("prevHkMods","meta");lpPutGblPref("homeHkKeyCode",0);lpPutGblPref("homeHkMods","")}else{lpPutGblPref("generateHkKeyCode",71);lpPutGblPref("generateHkMods",
"alt");lpPutGblPref("recheckHkKeyCode",73);lpPutGblPref("recheckHkMods","alt");lpPutGblPref("searchHkKeyCode",87);lpPutGblPref("searchHkMods","alt");lpPutGblPref("nextHkKeyCode",33);lpPutGblPref("nextHkMods","alt");lpPutGblPref("prevHkKeyCode",34);lpPutGblPref("prevHkMods","alt");lpPutGblPref("homeHkKeyCode",72);lpPutGblPref("homeHkMods","control alt")}lpPutGblPref("submitHkKeyCode",0);lpPutGblPref("submitHkMods","");lpPutGblPref("saveallHkKeyCode",0);lpPutGblPref("saveallHkMods","");lpPutGblPref("logoffHkKeyCode",
0);lpPutGblPref("logoffHkMods","");lpWriteAllPrefs()}
function lpWriteAllPrefs(){var b=opendb();createPrefsTable(b);b&&b.transaction(function(a){if(g_username_hash!=null&&g_username_hash!="")for(var c in g_userprefs)a.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",[g_username_hash,c,g_userprefs[c]],function(){},function(f,d){console_log(d)});for(c in g_gblprefs)a.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",["",c,g_gblprefs[c]],function(){},function(f,
d){console_log(d)})})}optionsData=[];optionsData.HotKeys=[];
function capturehk(b,a){var c="";c+=a.ctrlKey?"control":"";c+=a.metaKey?(c!=""?" ":"")+"meta":"";c+=a.altKey?(c!=""?" ":"")+"alt":"";c+=a.shiftKey?(c!=""?" ":"")+"shift":"";if(c==""||c=="shift")c=getBG().g_is_mac?"meta":"alt";if(a.keyCode==8||a.keyCode==127||a.keyCode==46)optionsData.HotKeys[b+"KeyCode"]=0;else if(a.keyCode<=32||a.keyCode==91)return;else optionsData.HotKeys[b+"KeyCode"]=a.keyCode!=0?a.keyCode:a.charCode;optionsData.HotKeys[b+"Mods"]=c;writeHotKeyValue(b)}
function writeHotKeyValue(b){var a=optionsData.HotKeys[b+"KeyCode"],c=document.getElementById(b),f="";if(a!=0){b=optionsData.HotKeys[b+"Mods"];if(typeof b!="string")b="";b=b.split(" ");for(var d in b){if(b[d]=="control")f+=gs("Ctrl")+"+";if(b[d]=="meta")f+=gs("Meta")+"+";if(b[d]=="alt")f+=gs("Alt")+"+";if(b[d]=="shift")f+=gs("Shift")+"+"}}if(a!=0){f+=a==33?gs("Page Up"):a==34?gs("Page Down"):a==35?gs("End"):a==36?gs("Home"):a==37?gs("Left"):a==38?gs("Up"):a==39?gs("Right"):a==40?gs("Down"):String.fromCharCode(a).toUpperCase();
c.value=f}else c.value=""}function fixhk(b,a){if(optionsData.HotKeys[b+"KeyCode"]<32){optionsData.HotKeys[b+"Mods"]="";writeHotKeyValue(b)}a.cancelBubble=true;a.stopPropagation()}var last_idle_check=0,idle_checker_started=false;function start_idle_checker(){if(last_idle_check==0&&!idle_checker_started)if(parseInt(lpGetPref("idleLogoffVal",0))>0){last_idle_check=lp_get_gmt_timestamp();idle_checker_started=true;setTimeout("idle_checker();",1E4)}}var last_active_time=0,enable_native_idle=false;
function idle_checker(){var b=parseInt(lpGetPref("idleLogoffVal",0));if(b>0){var a=b*60,c=function(d){var e=false,g=lp_get_gmt_timestamp();if(d=="active")last_active_time=lp_get_gmt_timestamp();else if(d=="locked")e=a<g-last_active_time;else if(d=="idle")e=true;d=true;if(last_idle_check!=0&&a!=0&&(e||a<g-last_idle_check)){console_log("IDLE CHECKER ISSUING LOGOFF: idleLogoffVal="+b+" isidle="+e+" limit="+a+" currtime="+g+" last_idle_check="+last_idle_check);lplogoff_if();d=false}if(d)last_idle_check=
g};if(enable_native_idle&&typeof chrome!="undefined"&&typeof chrome.idle!="undefined")chrome.idle.queryState(a,c);else if(have_nplastpass()&&typeof g_nplastpass.get_idle_ms=="function"){var f=g_nplastpass.get_idle_ms();f=parseInt(f/1E3);c(a<f?"idle":"active")}}setTimeout("idle_checker();",1E4)};
