/* Copyright 2010 Google */ (function(){var e=document;function f(a,c){return a.selectedIndex=c}function g(a,c){return a.display=c}var h="appendChild",i="length",j="prototype",k="selectedIndex",l="checked",m="value",n="style",o="options",p="createElement",q="firstChild",r="addEventListener";function s(){return"uid_"+(v=v+1||1)}var v;function w(a,c,b){var d=0;for(var t in c){var u=e[p]("option");u.value=t;u.text=c[t];u.A=d++;a[h](u);if(t==b)u.selected=true}if(!b)f(a,b==""?-1:0)}function x(a,c,b){var d=a[o][b];a.removeChild(d);f(a,a[o][b]?b:b-1);a=false;for(b=0;b<c[o][i];++b)if(d.A<c[o][b].A){c.insertBefore(d,c[o][b]);f(c,b);a=true;break}if(!a){c[h](d);f(c,c[o][i]-1)}}
function y(a,c,b,d){var t=z("langMapTemplate")[m];this.z=a;b.selectId=s();b.listId=s();b.addBtnId=s();b.removeBtnId=s();c.innerHTML=A(t,b);this.b=z(b.selectId);this.d=z(b.listId);this.l=z(b.addBtnId);this.m=z(b.removeBtnId);w(this.b,d);a=a.list();for(c=0;c<a[i];++c){b=a[c];for(d=0;d<this.b[o][i];++d)if(this.b[o][d][m]==b){x(this.b,this.d,d);break}}if(this.b[q])f(this.b,0);B(this);this.l[r]("click",C(this.n,this));this.m[r]("click",C(this.o,this))}
function B(a){a.l.disabled=!a.b[q]?"disabled":"";a.m.disabled=!a.d[q]?"disabled":""}y[j].n=function(){if(!(this.b[k]<0)){this.z.add(this.b[o][this.b[k]][m]);x(this.b,this.d,this.b[k]);B(this)}};y[j].o=function(){if(!(this.d[k]<0)){this.z.remove(this.d[o][this.d[k]][m]);x(this.d,this.b,this.d[k]);B(this)}};
function D(a,c,b){var d=z("urlListTemplate")[m];this.F=a;b.textId=s();b.reChkId=s();b.listId=s();b.addBtnId=s();b.removeBtnId=s();c.innerHTML=A(d,b);this.D=z(b.textId);this.B=z(b.reChkId);this.a=z(b.listId);this.G=z(b.addBtnId);this.p=z(b.removeBtnId);a=a.list();for(c=0;c<a[i];++c){b=a[c];d=e[p]("option");d.text=(b.type=="re"?"[RE]":"")+b.pattern;this.a[h](d)}E(this);this.G[r]("click",C(this.q,this));this.p[r]("click",C(this.r,this))}function E(a){a.p.disabled=!a.a[q]?"disabled":""}
D[j].q=function(){this.F.add(this.B[l]?"re":"str",this.D[m]);var a=e[p]("option");a.text=(this.B[l]?"[RE]":"")+this.D[m];this.a[h](a);f(this.a,this.a[o][i]-1);E(this)};D[j].r=function(){if(!(this.a[k]<0)){this.F.remove(this.a[k]);var a=this.a[k];this.a.removeChild(this.a[o][this.a[k]]);f(this.a,this.a[o][a]?a:a-1);E(this)}};var F=chrome.extension.getBackgroundPage();
function G(){this.c=F.translate.getUserOptions().clone();this.k=z("targetLangSel");this.e=z("autoDisplayChk");this.f=z("autoTransChk");this.h=z("autoDisplayMoreDiv");this.i=z("autoTransDiv");this.H=z("saveBtn");this.C=z("saveStatus")}G[j].g=function(){window._callback_=C(function(c){this.j=c.tl;H(this)},this);var a=e[p]("script");a.charset="UTF-8";a.src="http://translate.google.com/translate_a/l?client=tee&cb=_callback_";e.getElementsByTagName("head")[0][h](a)};
function H(a){w(a.k,a.j,a.c.targetLang()||"");a.k[r]("change",C(a.w,a));a.e.checked=a.c.autoDisplay();a.e[r]("change",C(a.s,a));a.f.checked=a.c.autoTrans();a.f[r]("change",C(a.t,a));a.I=new y(a.c.disabledLangs(),a.h[q],{title:"Excluded languages:"},a.j);a.J=new D(a.c.disabledUrls(),a.h.lastChild,{title:"Excluded URLs:"});a.K=new y(a.c.autoTransLangs(),a.i[q],{title:"Included languages:"},a.j);a.L=new D(a.c.autoTransUrls(),a.i.lastChild,{title:"Included URLs:"});a.H[r]("click",C(a.v,a));a.c.setOnSave(C(a.u,
a));I(a)}G[j].w=function(){this.c.set_targetLang(this.k[m])};G[j].s=function(){this.c.set_autoDisplay(this.e[l]);I(this)};G[j].t=function(){this.c.set_autoTrans(this.f[l]);I(this)};G[j].v=function(){F.translate.getUserOptions().assign(this.c);g(this.C[n],"")};G[j].u=function(){g(this.C[n],"none")};function I(a){if(!a.e[l])g(a.h[n],"none");if(!a.f[l])g(a.i[n],"none")}J(G,"OptionsControl");K(G,"init",G[j].g);function z(a){return e.getElementById(a)}function J(a,c){c=c.split(".");for(var b=window,d=0;d<c[i]-1;++d)b=b[c[d]]||(b[c[d]]={});b[c[c[i]-1]]=a}function K(a,c,b){a[j][c]=b}function A(a,c){return a.replace(/\{\{\$.*?\}\}/g,function(b){b=b.substr(3,b[i]-5);return String(c[b])||""})}
function C(a,c){c||(c=window);if(arguments[i]>2){var b=Array[j].slice.call(arguments,2);return function(){var d=Array[j].slice.call(arguments);Array[j].unshift.apply(d,b);return a.apply(c,d)}}else return function(){return a.apply(c,arguments)}};})();
